### ISSUE TITLE
RasterPacked save should take coordinate system into account

### ISSUE THREAD

**Issue by sebastianbaginski** [cogneco/ooc-kean#1002]
Could be useful for testing

**Comment by emilwestergren** [comment]
Can you explain what you mean?

**Comment by sebastianbaginski** [comment]
```ooc
bgr := RasterBgr open("file.png")
bgr coordinateSystem = CoordinateSystem YUpward
bgr save("file2.png")
```
file2.png is upside down

**Comment by emilwestergren** [comment]
But the coordinate system defines how the image is aligned in memory I think.

**Comment by sebastianbaginski** [comment]
Yes, but now you can assign this variable without any side effects on the image pixel layout. If `coordinateSystem` data member is meant to be freely changed, we need to either adapt all the methods accessing the pixel data to take the current value of this variable into account, or rearrange the image data on every write to this variable.

**Comment by emilwestergren** [comment]
It's not meant to be public. It should be set in the constructor and in some rare cases (like when recycling an Image) we can permit it.

**Comment by sebastianbaginski** [comment]
Well, this renders this issue invalid.
