### ISSUE TITLE
Incorrect referenceCount management in Image subclasses

### ISSUE THREAD

**Issue by sebastianbaginski** [cogneco/ooc-kean#1039]
```ooc
image := RasterBgr open(this sourceSpace)
image referenceCount _count == 0
```
Certainly this is not correct, as we have at least one valid reference to `image`.

What is the policy regarding the reference counter in images, who should increase it ? Should it be increased in constructor, or by the clients everywhere right after creating new image instance ? (in this case inside the `open` method).
@emilwestergren @simonmika

**Comment by emilwestergren** [comment]
It's only used for **strong** references and you create a strong reference when you increase it. Although this is not very robust since you can manually decrease the reference counter without having a strong reference to it. We should have a smart pointer implementation instead so you don't have to manually increase/decrease the ref counter.

**Comment by sebastianbaginski** [comment]
It is confusing as you never know if the object you receive in the function is a strong or weak reference, and calling `increase() / decrease()` on the object may or may not free it.

I'd like to have a smart pointers collection too, it seems like api would change a lot though (for example return `SharedPointer<RasterImage>` instead of `RasterImage` from `open`). Are you working on this ?

**Comment by emilwestergren** [comment]
No I'm not working on this. Yes there will be a lot of changes but if you can create a robust and efficient implementation I think it's worth it. Of course you need green light from Simon.

**Comment by sebastianbaginski** [comment]
OK let's hear what @simonmika says about it.

**Comment by simonmika** [comment]
@sebastianbaginski let us discuss this IRL.

**Comment by sebastianbaginski** [comment]
Alright, I get it now. Images are not reference counted until you start counting yourself. We need to look into this and improve, but for now this issue can be closed.
