### ISSUE TITLE
We need to have better interface for reference counted images

### ISSUE THREAD

**Issue by sebastianbaginski** [cogneco/ooc-kean#1049]
After talking to @simonmika I finally understand that even if `Image` has `referenceCounter` it is not always reference counted.
So basically image is not reference counted by default, it is only when you start using the reference counter. Despite that, it should be freed by reference counter `decrease()`.
I think this is quite confusing and we need a better, automated interface for reference counters.
Possbily related https://github.com/cogneco/ooc-kean/issues/815
@emilwestergren @simonmika

**Comment by simonmika** [comment]
Images should be freed using `free` like everything else. The only exception to that rule is when they are used with reference counting. That is the case when they are sent as content of a frame or when we are taking a planar image apart into its subimages.

**Comment by sebastianbaginski** [comment]
Yes and the confusion kicks in when you are receiving an image as parameter to function and want to simply temporarily bump the reference counter to simplify code, so you are not allowed to do this now:
```ooc
iwantbgr: method (bgr: RasterBgr);

method: func (image: RasterImage) {
    bgr: RasterBgr
    if (image instanceOf?(RasterBgr))
        bgr = image as RasterBgr
        bgr referenceCount increase()
    else
        bgr = RasterBgr convertFrom(image)
    iwantbgr(bgr)
    bgr referenceCount decrease()
}
```
Because it may or may not free the `image` parameter.
You need to do this instead:
```ooc
iwantbgr: method (bgr: RasterBgr);

method: func (image: RasterImage) {
    bgr: RasterBgr
    if (image instanceOf?(RasterBgr))
        bgr = image as RasterBgr
    else
        bgr = RasterBgr convertFrom(image)
    iwantbgr(bgr)
    if (image != bgr)
       bgr free()
}
```
which is not that bad, but I find previous code cleaner.

**Comment by simonmika** [comment]
I suggest that `convertFrom` always returns a new image.

**Comment by sebastianbaginski** [comment]
It does just that now, it simply calls `copy` if the types match.

**Comment by simonmika** [comment]
So we only need to do `free`.

**Comment by sebastianbaginski** [comment]
My point was to be able to skip the last `if` statement and always do `referenceCount decrease()` without checking if the image is reference counted or not. I just find it confusing to have a data member which you can touch only under some specific circumstances, hence this issue.

**Comment by simonmika** [comment]
You can always do free in this case.

**Comment by sebastianbaginski** [comment]
Yes and that's the whole point of this issue. You have cases when you call this and cases when you call that because you can't call this. Not the best interface in my opinion. Is manual reference counting the best we can do here ?

**Comment by simonmika** [comment]
Let us have a IRL discussion about this some time but for now I suggest focusing on more pressing issues.

**Comment by sebastianbaginski** [comment]
Sure.

**Comment by simonmika** [comment]
How things work now almost no one of us should ever need to increase or decrease the reference counter. It is normally done by the base filters we inherit. Only in the case when we want to save an incoming or on outgoing frame content without using the specialized modifier base class.

**Comment by emilwestergren** [comment]
Status?

**Comment by sebastianbaginski** [comment]
Reference counting is now done only in base filters, most of the time. 
I don't think we can come up with something better soon, I guess we can close this.
