### ISSUE TITLE
Lack of terminating null character can cause problems when interfacing Text class with system calls

### ISSUE THREAD

**Issue by sebastianbaginski** [cogneco/ooc-kean#1056]
Instances of `Text` are not ended with `'\0'` now. If we want to use `Text` instead of `String` with "low level" system calls we will need a way to make sure given Text instance is null-terminated, because this is what the C api expects most of the time.
Suggestions for the api:
```ooc
Text: cover {
...
    nullTermiated: func -> This {
        result := this take()
        if (result[result count - 1] != '\0')
            result = result + '\0'
        this free(Owner Receiver)
        result
    }
}
```
and call this like
```ooc
lowLevel: func (path: Text) {
    path = path nullTerminated() take()
    fopen(path raw, "r")
    path free(Owner Receiver)
}
```
Any other suggestions for names (`zeroTerminated` ?)
Another option is to add this as `Text` extension somewhere in the IO module to keep this out of public API.
@simonmika @marcusnaslund @emilwestergren

**Comment by marcusnaslund** [comment]
Wikipedia calls it `null-terminated`, so I prefer your original suggestion. Will we need it for anything other than lowlevel IO stuff?

**Comment by sebastianbaginski** [comment]
No, I don't think so.
A code is worth a thousand words, so simple example 
```ooc
t := t"a string" slice(2, 2)
printf("%s", t _buffer raw)
```
> string

**Comment by sebastianbaginski** [comment]
Alright, I will do that in `Text` class, write tests and we can go from there. Something like this will be needed anyway.

**Comment by marcusnaslund** [comment]
Great.

**Comment by simonmika** [comment]
We should never use a null terminated string. All operating system calls have to solve it themselves.

**Comment by sebastianbaginski** [comment]
This makes it impossible to replace String with Text in IO module.

**Comment by simonmika** [comment]
1. We should rewrite a new io compontent as the API is flawed anyhow.
2. It is the io compontents responsibility to handle the obscurities of the underlaying layers.

**Comment by sebastianbaginski** [comment]
That's why I suggested to add this as extension in IO module. You can't escape having it somewhere if you plan to use Text instead of String everywhere.

**Comment by simonmika** [comment]
module == source file
Therefore we needed another name, so:
component == use file

**Comment by sebastianbaginski** [comment]
Ok, whatever the name is, such function will need to be written one day and placed somewhere. This issue is still valid for current `Text` and will come back in the future.

**Comment by simonmika** [comment]
We should place that functionality in the new IO compontent.
