### ISSUE TITLE
Use override when implementing abstract functions?

### ISSUE THREAD

**Issue by emilwestergren** [cogneco/ooc-kean#1088]
Should we use override when implementing abstract functions? It seems the compiler gives different results. @thomasfanell @simonmika @fredrikbryntesson 

```ooc
BaseClass: class {
	function1: abstract func
}

InheritedClass: extends BaseClass {
	function1: override func { println("Hej") }
	//OR
	function1: func { println("Hej") }
}
```

**Comment by simonmika** [comment]
We should always use override when implementing abstract or virtual methods. Not doing it should generate a compiler error. If our version of rock does not work this way it is a bug.

**Comment by emilwestergren** [comment]
OK can someone create a better issue and then close this one?

**Comment by simonmika** [comment]
I think until magic has a symbol resolution built in @marcusnaslund has to enforce it as good as possible in the code review process. @fredrikbryntesson, can we output errors from rock when override is missing?

**Comment by marcusnaslund** [comment]
Sure, it's a general rule as of right now.

**Comment by fredrikbryntesson** [comment]
Sure, I can look into it later this week.

**Comment by thomasfanell** [comment]
@simonmika @fredrikbryntesson be warned, this will probably cause a lot of problems. I've seen several examples just the past week were rock segfaults when we override abstract methods (code that worked perfectly before we put override in the signature, by the way).

**Comment by marcusnaslund** [comment]
Confirmed, rock fails when in some places with `override` but works perfectly fine without, it seems.

**Comment by thomasfanell** [comment]
@simonmika @fredrikbryntesson as it turns out, this may very well be due to user error, according to some recent discoveries. The fact that rock does NOT complain if we're not using override may have promoted this error. So yes, we do need rock to complain about this.

This example is similar to one we just found in the other project:

```ooc
MathOperation: abstract class {
	calculate: abstract func (value1: Int, value2: Int, value3: Int) -> Int
}
Add: class extends MathOperation {
	init: func
	calculate: override func (value1: Int, value2: Int, value3: Int) -> Int {
		value1 + value2 + value3
	}
}
Pow: class extends MathOperation {
	init: func
	// shadow calculate(), using override here would cause a compiler error (as it should)
	// note that we're missing the third argument in the signature (user error)
	calculate: func (value1: Int, value2: Int) -> Int {
		result := value1
		for (i in 1 .. value2)
			result *= value1
		result
	}
}
```

**Comment by simonmika** [comment]
@fredrikbryntesson Can we introduce a required `new` keyword?

**Comment by marcusnaslund** [comment]
We've decided on `override` everywhere, and rock will in a near future enforce it, so I guess this is solved.
