### ISSUE TITLE
Do not allow negative sizes for FloatBox, IntBox

### ISSUE THREAD

**Issue by bettinaselig** [cogneco/ooc-kean#1106]
When `FloatBox` or `IntBox` is initialised with a negative vector as size, the member variables `leftTop` and `size` need to be recalculated. 

Something like:
```
init: func@ (point: FloatPoint2D, vector: FloatVector2D) {
    if (vector x < 0) {
        point x += vector x
        vector x = -vector x
    }
    if (vector y < 0) {
        point y += vector y
        vector y = -vector y
    }
    this leftTop = point
    this size = vector
}
```

Decided in IRL discussion after closing https://github.com/cogneco/ooc-kean/pull/1054.

**Comment by marcusnaslund** [comment]
I can do this.
