### ISSUE TITLE
Move os/Time to the sdk root

### ISSUE THREAD

**Issue by marcusnaslund** [cogneco/ooc-kean#1130]
`Time` is rather unique in the `sdk/os` directory in the sense that we use it in a lot of places, but the rest of the sdk does not. 

We could move it to the sdk root and auto-import it through `sdk.use`, and thereby remove all the explicit `os/Time` imports. Thoughts @sebastianbaginski ?

**Comment by sebastianbaginski** [comment]
Sure, why not.
