### ISSUE TITLE
Missing abs for float

### ISSUE THREAD

**Issue by zhaihj** [cogneco/ooc-kean#114]
ooc-unit can not be compile in current ooc-kean because of lacking member function `abs`. A solution may be adding abs in lang/Numbers, for example:

	extend LDouble{
		abs: func ~ooc -> This{
			this > 0. ? this : -this
		}
	}

**Comment by davidhesselbom** [comment]
You're right. At some point there was a problem that both `math.ooc` and `lang/Numbers.ooc` had defined abs functions, so I removed the one in `lang/Numbers.ooc`. It seems I forgot to update `ooc-unit` along the way. Will fix shortly, thanks!
