### ISSUE TITLE
Quaternion cleanup

### ISSUE THREAD

**Issue by emilwestergren** [cogneco/ooc-kean#1156]
## Suggestions for improving the Quaternion implementation:

**Replace FloatPoint3D with FloatVector3D where needed**
- [ ] Imaginary part should be a `FloatVector3D` instead of `FloatPoint3D`

**Remove superfluous properties**
- [x]  `logarithmImaginaryNorm ::= ((this logarithm) imaginary) norm`
- [x]  `rotation ::= 2.0f * this logarithmImaginaryNorm`

Are these really needed? If so, I think they are badly named and/or confusing.

**Improve local variable names**
```ooc
point3DNorm := this imaginary norm
if (point3DNorm != 0)
	result = This new(norm log(), (this imaginary / point3DNorm) * ((this real / norm) acos()))
```

```ooc
direction: FloatPoint3D {
	get {
		quaternionLogarithm := this logarithm
		quaternionLogarithm imaginary / quaternionLogarithm imaginary norm
	}
}
```
There are lots of poor local variable names which should be improved, these are two examples:
- [x]  `point3DNorm`
- [x]  `quaternionLogarithm`

@simonmika @marcusnaslund @niklasborwell please give your opinions and I will modify this issue if we agree to add/remove anything.

**Comment by marcusnaslund** [comment]
Properties like `direction` above should also be formatted like this:
```ooc
direction: FloatPoint3D { get {
        quaternionLogarithm := this logarithm
        quaternionLogarithm imaginary / quaternionLogarithm imaginary norm
}}
```

**Comment by emilwestergren** [comment]
Any objections against the proposed changes?

**Comment by niklasborwell** [comment]
No

**Comment by marcusnaslund** [comment]
Go for it.

**Comment by emilwestergren** [comment]
@tomasmahlberg are you working on this?

**Comment by tomasmahlberg** [comment]
Not at the moment, no. I have a local branch that changes `createRotation` to `createFromAxisAngle` but did not push yet.

**Comment by marcusnaslund** [comment]
We're not changing the type of the imaginary part?

**Comment by emilwestergren** [comment]
No, I'm not sure if we should so I'll just leave it be.
