### ISSUE TITLE
Test `ToRaster` crashes

### ISSUE THREAD

**Issue by zhaihj** [cogneco/ooc-kean#128]
Currently test `ToRaster` creashes because the super function of `RasterBgr init` is not correctly called. 
It is expected to call `RasterPacked init` but finally generated code calls `RasterImage init` because rock is simply search for super() in all functions.

Even though this is a bug of rock, we can get around by adding suffixes to `RasterImage init` or `RasterBgr init`'s `super`, for example:

    RasterImage: abstract class extends Image{
        init: func ~addedsuffix (size: IntSize2D, align: Int, verticalAlign: Int) {
            super(size)
            this _align = align
            this _verticalAlign = verticalAlign
        }
    }

Or directly point out which super should be called in `RasterBgr init`:

    init: func (size: IntSize2D, align := 0, verticalAlign := 0) {
        //~allocate is the function in RasterPacked
        //walk around for rock's bug
        super~allocate(size, align, verticalAlign)
    }

**Comment by davidhesselbom** [comment]
I remember having problems with this earlier and ended up having to use an alias, like you say. Apparently the problem has come back after later changes. I'll look into this, thanks for letting us know.

**Comment by zhaihj** [comment]
@davidhesselbom 
https://github.com/cogneco/ooc-kean/blob/master/test/draw/RasterYuvSemiplanarTest.ooc
RasterYuvSemilanar Test fails because `for (i in 0..1) {` is not correctly commented out ....

**Comment by davidhesselbom** [comment]
Haha. Thanks :)
