### ISSUE TITLE
Buffer is not set when initialized raster from rasterImage

### ISSUE THREAD

**Issue by zhaihj** [cogneco/ooc-kean#141]
m := RasterMonochrome open(source)
        image := RasterBgra new(monochrome)
        image save(destination)

Buffer is null in `image save`, because _buffer is defined in `RasterPacked`, but `RasterBgra -> init ~fromRaster` treat input as `RasterImage` and just passed it to `RasterImage`.

I think it need some code like:

    if(original instanceOf?(RasterPack)){
        _buffer = original _buffer
        _stride = original _stride
    }

or just add `init ~fromRaster(RasterPack)` ?

**Comment by davidhesselbom** [comment]
I'll look into this shortly. Thanks for the info!

**Comment by davidhesselbom** [comment]
Hmm, this whole chain of constructors is broken except for in a few special cases. I should be able to fix it within a few days, though.

**Comment by davidhesselbom** [comment]
Made some progress here, but I'm not finished yet.


https://github.com/davidhesselbom/ooc-kean/tree/rasterimage-fix

If you want to convert from one type of RasterImage to another, you need to use the `convertFrom` function (I'm updating the test to show this). The `init (original: RasterImage)` function will create a new, empty RasterImage with the same size, but it will not copy data or convert colors. I've fixed the issue where the Buffer is null when calling this constructor.

`converstFrom` is still broken, however. It seems that get properties don't always work. For instance, in `RasterBgra` `convertFrom`, the call `destination := result _buffer _pointer` will work but `destination := result _buffer pointer` will result in a segfault. I tried to build a smaller program to replicate the issue, but to no success.

The only working conversion that I've been able to confirm so far is from Monochrome to Bgra:
```ooc
image := RasterMonochrome open(source)
bgra := RasterBgra convertFrom(image)
bgra save(destination)
```
The conversion is wrong and results in an incorrect image, but at least it doesn't crash...

**Comment by zhaihj** [comment]
I've tried this, but it creashed...

    image := RasterMonochrome open(source)
    bgra := RasterBgra convertFrom(image)
    bgra save(destination)


One problem is that `convertFrom` uses `RasterBgra new(ReasterImage)`, which is implemented as:

	init: func ~fromRaster (original: RasterImage) { super(original) }


Only `RasterImage` implements this `init`, so the call chain will be : `RasterBgra init -> RasterImage init`. Clearly `_buffer` is not initialized.

My solution is adding the following code to `RasterPacked`:


    init: func ~fromRaster(original: RasterImage){
        super(original)
        this init(original size)
    }

**Comment by davidhesselbom** [comment]
No, that's not correct. In my fork, which I linked to above, the call `result := RasterBgra new(original)`
calls `( init: func ~fromRaster (original: RasterImage) { super~fromOriginal(original) }` which calls the [same function](https://github.com/davidhesselbom/ooc-kean/blob/rasterimage-fix/source/draw/RasterPacked.ooc#L41) in `RasterPacked`, which creates a buffer.

**Comment by davidhesselbom** [comment]
Well, I got RasterBgra-RasterMonochrome conversion, and vice versa, to work in my fork. The conversion will not work if stride != width, however. I will merge when I feel happy about the code (it's messy right now) and I get the Bgr to work as well.

**Comment by davidhesselbom** [comment]
... and this is likely going to take another few weeks, at this rate.

**Comment by davidhesselbom** [comment]
#274 fixes conversions between RasterBgra, RasterBgr and RasterMonochrome, at least for images where stride == width. It's a start, at least.

**Comment by davidhesselbom** [comment]
#277 fixes RasterYuv420Semiplanar conversion to and from RasterBgra, RasterBgr, RasterMonochrome. RasterYuv420Planar is still broken, and I can't figure out why. Somewhy its `_allocate` function returns junk instead of `(RasterMonochrome, RasterMonochrome, RasterMonochrome)`.

**Comment by davidhesselbom** [comment]
#280 fixes the broken constructors in RasterYuv420Planar, which didn't work because rock apparently thinks that when it can choose between a local variable `y` and a property `y` in the same class (i.e. `this y`), it's a good idea to choose the property `y`.

Unfortunately, converting from one format to RasterYuv420Planar doesn't work very well, and I think it's because closures don't work the way I expect them to. For instance, adding `"y: #{y}" println()` [here](https://github.com/cogneco/ooc-kean/blob/master/source/draw/RasterYuv420Planar.ooc#L127) makes conversion work perfectly. Without that call, you get segfaults, and I haven't been able to figure out why.

**Comment by davidhesselbom** [comment]
I don't think we're going to get anywhere with this anytime soon, and I also don't think anyone much cares. Closing.
