### ISSUE TITLE
Static member is used as a function

### ISSUE THREAD

**Issue by zhaihj** [cogneco/ooc-kean#302]
In `sdk/os/Time.ooc`:
```ooc
Time: class{
    __time_microsec_base := static This runTime
    __time_millisec_base := static This __time_microsec_base() / 1000
```

Here `__time_microsec_base` seems to be a static member, but it is called as a function.

**Comment by davidhesselbom** [comment]
Well... `This runTime` is a function, so `__this_microsec_base` is a static function pointer which, when used as a function, must have parentheses...? I'm just guessing, though.

**Comment by davidhesselbom** [comment]
Another way of writing it might be
```ooc
Time: class{
    __time_microsec_base: static func -> UInt { This runTime() }
    __time_millisec_base := static This __time_microsec_base() / 1000
```

**Comment by zhaihj** [comment]
Ah, I see. You're right.

In fact, I got a gcc error when using os/Time:
```
.ooc_libs/ooc-kean/source/sdk/os/Time.ooc: In function ‘os_Time__Time___load__’:
.ooc_libs/ooc-kean/source/sdk/os/Time.ooc:232:49: error: incompatible types when assigning to type ‘lang_types__Closure {aka struct _lang_types__Closure}’ from type ‘lang_Numbers__UInt (*)() {aka unsigned int (*)()}’
```

It may be better to create a function like this? (not sure though)
```ooc
    __time_microsec_base := static (This runTime, null) as Func->UInt
    __time_millisec_base := static This __time_microsec_base() / 1000
```

**Comment by davidhesselbom** [comment]
I guess "better" is subjective. Personally, I don't see a problem with having function pointer members - being able to assign functions to functions as if they were simple variables is a kind of cool feature with ooc that I haven't seen elsewhere (other than in functional programming languages).

**Comment by davidhesselbom** [comment]
Thanks for the heads-up, though - I appreciate being notified of anything strange in the code.

**Comment by zhaihj** [comment]
Yes, `as Func` looks ugly and shouldn't be said as "better". I suggested it just because current rock does not handle first-class functions well enough.

My rock generates incorrect c sources for  ` __time_microsec_base := static This runTime`, where right hand is `Func->UInt` but left hand is a closure. Assignment between them causes a gcc error. 
Related issue: https://github.com/fasterthanlime/rock/issues/439

Btw, `lang/Backtrace` also uses "function pointer", you can find it at `lang/Backtrace.ooc : line50`.

**Comment by davidhesselbom** [comment]
I'm not sure I understand. Are you saying the the `sdk/os/Time.ooc` in `ooc-kean` generates incorrect C sources when using the official version of rock? Can you give me an ooc snippet to demonstrate? I don't think we've used all the functions in `Time` in our project, and I haven't looked at the C sources, but everything seems to work fine for me. I'm using our own, inofficial version of rock, though.

**Comment by zhaihj** [comment]
Rock --version : `rock 0.9.11-head codename sapporo, built on Tue Jul 28 19:07:01 2015`


Using
```ooc
    __time_microsec_base := static This runTime
    __time_millisec_base := static This __time_microsec_base() / 1000
```

rock reports a gcc error:
```
.ooc_libs/ooc-kean/source/sdk/os/Time.ooc: In function ‘os_Time__Time___load__’:
.ooc_libs/ooc-kean/source/sdk/os/Time.ooc:232:49: error: incompatible types when assigning to type ‘lang_types__Closure {aka struct _lang_types__Closure}’ from type ‘lang_Numbers__UInt (*)() {aka unsigned int (*)()}’
C compiler failed on module os/Time from sdk, bailing out
```

Generated `Time.c`:

```c
    os_Time__Time_class()->__time_microsec_base = os_Time__Time_runTime;
    os_Time__Time_class()->__time_millisec_base = ((lang_Numbers__UInt (*)(void*)) os_Time__Time_class()->__time_microsec_base.thunk)(os_Time__Time_class()->__time_microsec_base.context) / 1000;
```

Definition of `__time_microsec_base`:
```c
struct _os_Time__TimeClass {
    struct _lang_types__ClassClass __super__;
    lang_types__Closure __time_microsec_base;
    lang_Numbers__UInt __time_millisec_base;
};
```

Definition of `os_Time__Time_runTime`:
```c
lang_Numbers__UInt os_Time__Time_runTime() { ... }
``


After changing to 
```ooc
     __time_microsec_base := static (This runTime, null) as Func->UInt
     __time_millisec_base := static This __time_microsec_base() / 1000
```
Evenything works.
