### ISSUE TITLE
Saving images to non-existing folders

### ISSUE THREAD

**Issue by davidhesselbom** [cogneco/ooc-kean#378]
`ImageFileTest` starts by doing this:
```ooc
		File new("test/draw/output") mkdir()
```
... but since the `find` command used in `test.sh` returns a list that is ordered by folder, but not alphabetically, `ImageFileTest` is not guaranteed to run before the other test in `draw` that need to put things in the `test/draw/output` folder. If the folder doesn't exist, tests fail locally, but on Travis, it causes the test to crash. 

There are several solutions and/or workarounds to this, but I'm not sure which one is a better idea:

1. Sort the tests alphabetically before running them
    - Listed for completeness, this a terrible idea. What if we add another test named `AlphaChannelTest` or something, do we move the `mkdir()` call there?
1. Let each test that needs a particular folder for its output create that folder, i.e. copy the `mkdir()` call code into each of those tests.
    - Leads to duplicate code, and is easy to forget. Tests may pass a few times because you got lucky, and suddenly fail later on.
1. Let the `save` function in the `RasterImage` classes create folders if necessary. Possibly, add a parameter for this in the `save` function and throw exceptions if an image is saved to a non-existing folder.
    - Actually, there is currently no error handling at all for the `save` function. It returns an `Int`, but which is consistently ignored. This probably deserves an issue of its own...
    - This solution has the upside that, while it is easy to forget to add the flag for creating the folder if it doesn't exist, you will get an exception if you forget, instead of a test that crashes for unknown reasons. You can still get lucky, though, and the error will manifest itself much later.
1. Commit a `.keepme` file or similar to make sure the output folder always exists (the empty folder itself cannot be commited in Git). 
    - This will help make sure the tests run regardless of the order they were executed, but it doesn't seem like a reliable way of doing things.

**Comment by sebastianbaginski** [comment]
Since this is marked as *help wanted*:
5. Create a base class `AbstractDrawTest extends Fixture`, put `mkdir("test/draw/output")` call in its constructor and let all test classes that require drawing extend this class instead of Fixture ?

**Comment by davidhesselbom** [comment]
Thanks, other people's input is what the label is for. 

Using a base class would fix things for the draw tests, but what about the other parts of our program that need to store things in folders that may not exist at the time?

**Comment by sebastianbaginski** [comment]
Good question. I'm used to solution 3., where each component is allowed to create needed folders whenever it needs to. Without any flags, exceptions etc. just simply create the needed folder structure on demand.
It has lead to a funny bug once (when you type something like `mkdir("path")` instead of `mkdir(path)`), but still, worked well most of the time.

**Comment by davidhesselbom** [comment]
The problem with creating folders on demand is that you don't know whether you have permissions to do that on the system you're on. I think we'll need some form of exception handling either way.

**Comment by sebastianbaginski** [comment]
True. I don't know how to solve this, though, but I can at least add error checking for `save` functions to image tests if you want.

**Comment by davidhesselbom** [comment]
You could, but I don't think having to do that in every test is the right way to go.

**Comment by simonmika** [comment]
Go for number 3. Create the necessary folders when saving. The best would be if that was hidden in the file system abstraction.

**Comment by davidhesselbom** [comment]
The file is saved by StbImage, so it has nothing to do with `File` in ooc, it's just a path. I could add the check in `RasterImage save` and let each of the derived classes call `super()`.

**Comment by simonmika** [comment]
It is an odd use of `super()`.

**Comment by davidhesselbom** [comment]
Really? Something happens in the base class's function, and you want it to happen in the overrides of the function, too - how is that an odd use of `super()`?

**Comment by simonmika** [comment]
Having a base function called `save` that has an implementation but does not actually save the image seams odd.

**Comment by davidhesselbom** [comment]
Okay, so let `stb_image_write.c` handle it?

**Comment by davidhesselbom** [comment]
Actually, the `StbImage writePng` call could be moved to `RasterImage save` and the derived classes shouldn't need their own implementation (except when they need to be converted first, such as in the YUV ones, and even then, they should be able to call `save` on the converted result). I think that would be the best solution anyway, we don't need `StbImage writePng` calls in 6 places.

**Comment by simonmika** [comment]
So move save to RasterImage or even Image and instead have a convert method that converts the Image to Rgba.

**Comment by davidhesselbom** [comment]
Yes, there are `convert` functions, but it's nice to be able to call `save` directly on e.g. a `RasterYuv420Semiplanar` so you don't have do
```ooc
		bgr := RasterBgr convertFrom(this)
		result := bgr save(filename)
		bgr free()
```
manually whenever you want to save a `RasterYuv420Semiplanar` to disk. So the `save` function in `RasterYuv420Semiplanar` (shown above) will remain the same after I make the changes I suggested.

**Comment by davidhesselbom** [comment]
I moved the StbImage `writePng` calls into `RasterPacked`, not `RasterImage`, because `RasterPacked` has the `bytesPerPixel` property and `buffer` member, which don't exist in `RasterImage` but which must be used in the `writePng` call somehow. Good enough for now.
