### ISSUE TITLE
ooc-unit: Print expected and actual value when tests fail

### ISSUE THREAD

**Issue by davidhesselbom** [cogneco/ooc-kean#397]
```ooc
			expect(rasterFromGpu distance(correctImage), is equal to(0.0f))
```
If `rasterFromGpu distance(correctImage)` > 0, we have no idea what the actual value is or what a suitable threshold for a `within` might be. 

Modify `ooc-unit` so that when an `expect` fails, it prints both the expected value and the actual value, not just the name of the test, e.g.
```
GpuImageTranslationTest ..f failed
  -> 'GPU translate Z (BGRA), expected 0.0, was 0.7543456'
```

**Comment by davidhesselbom** [comment]
Partially fixed by #405.

**Comment by marcusnaslund** [comment]
What more remains?

**Comment by davidhesselbom** [comment]
I think this has been fixed by now, yes.

**Comment by davidhesselbom** [comment]
Nope &mdash; it doesn't work for `String`, and I think it should.

**Comment by marcusnaslund** [comment]
Why? Don't we want to replace all of that with `Text`?

**Comment by davidhesselbom** [comment]
Mmm. A lot of work, by comparison, but I suppose  it *is* a better long-term solution.
