### ISSUE TITLE
Tests for morphomological methods in BoolVectorList.

### ISSUE THREAD

**Issue by bettinaselig** [cogneco/ooc-kean#408]
Add tests for `erosion()`, `dilation()`, `opening()` and `closing()`.

**Comment by marcusnaslund** [comment]
@bettinaselig Could you explain in short what these functions are meant to do?

**Comment by davidpiuva** [comment]
I think it should be "morphological".

**Comment by bettinaselig** [comment]
"morphological" yes... sorry typo.

**Comment by davidhesselbom** [comment]
`morphomological` sounds pretty cool though, I think it would have made a nice name for magic.

**Comment by marcusnaslund** [comment]
This is part of the larger issue #492  - should I close this or keep both?

**Comment by marcusnaslund** [comment]
Either way, this will be resolved by #505 .
