### ISSUE TITLE
TimeSpan test fails on Windows

### ISSUE THREAD

**Issue by sebastianbaginski** [cogneco/ooc-kean#433]
It could be nice to find out why.

**Comment by davidpiuva** [comment]
Does other 64-bit operations from ooc work?

**Comment by sebastianbaginski** [comment]
Good question. How do I verify this ? Almost every test in *math* succeeds (except https://github.com/cogneco/ooc-kean/issues/435), and I assume we do use some 64-bit operations there ?

**Comment by davidpiuva** [comment]
sizeof(int) should reveal the default size of integers. 32 or 64 bits.

sizeof(void*) should reveal the default size of pointers. Most C compilers let pointers have the size of an integer but some compilers have double size pointers.

**Comment by davidhesselbom** [comment]
I think its `Int size` rather than `sizeof(int)`, but yes.

**Comment by davidpiuva** [comment]
size in ooc is not equivalent for special cases where references are followed automatically in order to measure the size of classes instead of their pointers.

**Comment by sebastianbaginski** [comment]
It is just a simple error in floating point computations, I will fix this later.

**Comment by sebastianbaginski** [comment]
Probably related to different representations of `double` on linux and windows. I don't think it's worth to dig deeper into it.
