### ISSUE TITLE
Code coverage in tests

### ISSUE THREAD

**Issue by davidhesselbom** [cogneco/ooc-kean#446]
E.g. `FloatBox2DTest` doesn't test any of the functions `union`, `intersection`, `bounds`, `createAround`, `adaptTo`... 

Is there any way we can detect this kind of thing automatically? A list of functions and properties in cover/class should be easy to extract from an `ooc` file, and at the very least, a tool for code coverage should be able to detect when any of those functions/properties are not used a single once in a test for that cover/class, especially when the test file is named after the cover/class itself. Would this be a suitable task for magic?

**Comment by marcusnaslund** [comment]
Yes, I can take a look at this.
Do we want it as part of magic though? Maybe in the future, but for now there seem to already be a lot of TODOs in the magic source and I don't want to start messing around with it. For now I'll write a separate script, scan the files, see if I can add some missing tests to make it more complete, and then we can see in the future if we can/want to integrate it into magic. OK?

**Comment by sebastianbaginski** [comment]
I'm just wondering, maybe it is possible to use `gcov` to do that. We have the C code generated for both kean ooc source and unit test ooc code, so it should be possible to analyze the C code coverage using `gcov`. It is very easy to use and pretty accurate, but requires to compile the binary with `-fprofile-arcs -ftest-coverage` flags. Here is nice manual https://gcc.gnu.org/onlinedocs/gcc/Gcov.html . I used it to analyze the test coverage for C++ source, it worked great.
There is another tool that generates pretty html reports for gcov, I can't remember the name now, though.
Having it in magic does sound great, but maybe `gcov` is worth giving a shot ?

**Comment by marcusnaslund** [comment]
My first idea was to regex everything of the type `<something>: func`, `<something>: func ~<something>`, `<something> ::=`, `operator <something>`, make a list of all of those `<something>`s, and search the corresponding test file for what is not in it.
We would miss the overloads but we can make a list of those rows and do manual inspection. This would at least give us a much cleaner output than the flood of data from `gcov`.
But we might want to make sure we test all lines of code, not just all functions? Then `gcov` is a better option I suppose.

**Comment by davidhesselbom** [comment]
Alright, sure, a tool that analyzes the C code instead would work, too. It just seemed like an easy enough job to make a tool of our own, unlike, say, what Valgrind does :)

**Comment by sebastianbaginski** [comment]
I don't know, really. I guess anything that can give us a hint about missing test cases is great :)

**Comment by davidhesselbom** [comment]
I haven't even tried gcov yet, but if it tells you about all the functions in your program that you didn't call, we need some way to ignore the things in the SDK, because a lot of it will be part of the program even in a simple test like the one for `FloatPoint2D`.

**Comment by sebastianbaginski** [comment]
Yeah it kinda does that. That's why I used the html reports to read the output, here it is http://linux.die.net/man/1/lcov . Example output https://subhoworld.files.wordpress.com/2015/01/screenshot-from-2015-01-09-143047.png

**Comment by marcusnaslund** [comment]
Ah, generated HTML files make it a lot easier to process. Will look into it.

**Comment by marcusnaslund** [comment]
Using `gcov` meant a lot of manual processing because it of course profiles the C code and not the ooc code, and you get a lot of data. I went with the simpler approach of regexing and it works very nicely. Will upload the script somewhere when I've polished it a bit more.

**Comment by marcusnaslund** [comment]
3.5 months later, I've changed my mind. `gcov` works very nicely. I will be uploading a script for this soon.
