### ISSUE TITLE
AppVeyor

### ISSUE THREAD

**Issue by davidhesselbom** [cogneco/ooc-kean#447]
Now that we have Circle CI in place for running our tests in Ubuntu, and now that we are building for Windows as well, we should look into using [AppVeyor](http://www.appveyor.com/) to run our tests in Windows. It works similarly to Circle CI and is free for open source projects. I'd be happy to help, given the time to do so.

**Comment by davidhesselbom** [comment]
Any progress here, @jonathanudd ? If not, unassign yourself to indicate that no one is working on it.

**Comment by marcusnaslund** [comment]
This is working now, so closing it.
