### ISSUE TITLE
ImageFileTest fails on Windows

### ISSUE THREAD

**Issue by sebastianbaginski** [cogneco/ooc-kean#450]
Fails only on this test case
```ooc
this add("convert RasterBgra to RasterYuv420Semiplanar", func {
	source := "test/draw/input/Barn.png"
	destination := "test/draw/output/RasterBgra-RasterYuv420Semiplanar-RasterMonochrome.png"
	bgra := RasterBgra open(source)
	yuv420 := RasterYuv420Semiplanar convertFrom(bgra)
	monochrome := RasterMonochrome convertFrom(yuv420)
	monochrome save(destination)
})
```
Test works if you replace `Barn.png` with `Flower.png`.

**Comment by davidhesselbom** [comment]
Could be because `Barn.png` is 957 pixels high, which could cause problems when converting to an image format like Yuv420Semiplanar.

**Comment by davidhesselbom** [comment]
We could throw errors when attempting to open files with odd dimensions to make things easier for ourselves...

**Comment by sebastianbaginski** [comment]
It results in segmentation fault from stb_image_write, at the very last step of this test.
I checked and every image seems to have the correct size after converting.

**Comment by davidhesselbom** [comment]
Yes, and this may be a result of an incorrectly allocated `ByteBuffer` and memory being written in the wrong places, which only manifests itself in `stb_image_write`. Maybe. I'm pretty sure that if you modify the size of `Barn.png` to 956 pixels, it'll work.

**Comment by sebastianbaginski** [comment]
What's even more funny is the fact that it works when you run it with debugger. I guess it must be a uninitialized memory somewhere, which defaults to `0` when you run the program with gdb.

**Comment by davidhesselbom** [comment]
Yes, when you use a debugger, you run the program in a sand box, I think. You could try running the test with valgrind and see if it reports any invalid memory reads/writes.

**Comment by sebastianbaginski** [comment]
You were right, it doesn't crash with an even size.
