### ISSUE TITLE
PointerVector, PointerVectorList and HashDictionary

### ISSUE THREAD

**Issue by thomasfanell** [cogneco/ooc-kean#460]
Currently, [PointerVector](https://github.com/cogneco/ooc-kean/blob/master/source/collections/PointerVector.ooc),  [PointerVectorList](https://github.com/cogneco/ooc-kean/blob/master/source/collections/PointerVectorList.ooc) and  [HashDictionary](https://github.com/cogneco/ooc-kean/blob/master/source/collections/HashDictionary.ooc) does not appear to be used in any of our projects. Do we want to use these for something? Can anyone think of a case where one of these would be better to use?

**Comment by davidhesselbom** [comment]
`PointerVectorList` could be useful as a replacement for `VectorList` where `T` is known to be an object, for performance reasons. I can't think of anywhere this would actually help, though. It would be better to create dedicated, non-generic versions of e.g. `FloatVectorList`.

**Comment by marcusnaslund** [comment]
`HashDictionary` seems like a reasonable thing to have in any standard library. The first two I'm not so sure about, though. Why were they written in the first place?

**Comment by davidhesselbom** [comment]
The first two I just explained, but `HashDictionary` was meant to be used for something before we realized how difficult it was to handle memory whenever `String` was involved.

**Comment by marcusnaslund** [comment]
It should be pretty simple to rewrite `HashDictionary` to use `Text` instead of `String` as key, right?

**Comment by davidhesselbom** [comment]
Probably, but I don't think we'll be switching back now anyway, so don't spend time on it right now.
