### ISSUE TITLE
Cast warning in Format.ooc

### ISSUE THREAD

**Issue by davidhesselbom** [cogneco/ooc-kean#467]
Currently, there is a warning when building:
```ooc
[CC] lang/Format
/home/dhesselbom/versioned/ooc/ooc-kean/source/sdk/lang/Format.ooc: In function ‘lang_Format__getEntityInfoOne’:
/home/dhesselbom/versioned/ooc/ooc-kean/source/sdk/lang/Format.ooc:455:34: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
             info precision = T as Int
                                  ^
```
It's the result of my desperate attempts to fix memory leaks originating from the `toString` functions in various numeric types and has been there for a long time. It would be awfully nice to get it fixed...

**Comment by marcusnaslund** [comment]
When is line 455 ever even called?

**Comment by davidhesselbom** [comment]
Currently, I don't think it ever is. I tried commenting the line out and everything still works... and you wouldn't be able to call `"*.*f" formatFloat(Float pi, 3, 7)` anyway. Thanks for the obvious fix.

**Comment by marcusnaslund** [comment]
I noticed the same thing. Awesome.
