### ISSUE TITLE
File test fails on Windows

### ISSUE THREAD

**Issue by sebastianbaginski** [cogneco/ooc-kean#474]

**Comment by sebastianbaginski** [comment]
Looks like `file dir?()` returns `false` for directories on Windows.

**Comment by davidpiuva** [comment]
dir in the Windows API returns the folder path to a given file and nothing if the file does not exist.

**Comment by davidhesselbom** [comment]
Does it have anything to do with delimiters?

**Comment by sebastianbaginski** [comment]
I don't think so, as it returns `true` for `exists?()` call on the same object :) And the directory is actually created. 
I think I will just use simple test for `FILE_ATTRIBUTE_DIRECTORY` instead of calling `FindFirstFile` when testing for `dir?()`

**Comment by davidhesselbom** [comment]
I have no idea how windows handles files in C, and I also have no way to test this right now, so you do what you think is best, I think.

**Comment by sebastianbaginski** [comment]
I will simply use the code from `exists?` function, but with different flag.
