### ISSUE TITLE
"empty" as a function or property name

### ISSUE THREAD

**Issue by davidhesselbom** [cogneco/ooc-kean#475]
It is generally considered a bad idea to use words like "empty" for function/property names, because it's not clear whether it's a verb or an adjective. There are many places in our codebase where `empty` is a property that returns a `Bool`. Should those be changed into `isEmpty`? Or should it be obvious that
1. `This empty` returns an "empty" instance of something,
2. `this empty` returns a bool stating whether an instance is "empty", and
3. `this empty()` "empties" an instance?

**Comment by simonmika** [comment]
My thinking is currently:
1. use `This empty`
2. `this empty` or `this isEmpty`, not sure
3. in this case I suggest using `this clear()` instead

**Comment by davidhesselbom** [comment]
That's all I need for #442, but I'm leaving this open until we've reached a decision about number 2.

**Comment by marcusnaslund** [comment]
There are a lot of `empty` properties in math, so maybe before #491 it would be nice to have consensus on number 2.

**Comment by davidpiuva** [comment]
I prefer isEmpty for clarity.

**Comment by davidhesselbom** [comment]
Yes, I'd like some consistency about this. And I agree `isEmpty` is better for properties, but if we choose to go with `isEmpty`, should all properties that return a `Bool` start with `is` for consistency? I wouldn't mind if they did.

**Comment by emilwestergren** [comment]
I agree with Dr. Hesselbom, if we go with `isEmpty` then we need to be consistent.

**Comment by marcusnaslund** [comment]
To revive this and hopefully reach a decision: I've also seen the `identitiy` property which in fact did not check whether an instance was the identity, but rather created a new identity element. I think this was in `FloatRotation3D`. Not exactly clear as it is now.

**Comment by davidpiuva** [comment]
`makeIdentity` and `isIdentity` would separate explicitly.

**Comment by emilwestergren** [comment]
I prefer
`identity` - returns new
`isIdentity` - return bool

**Comment by marcusnaslund** [comment]
Yes, I also agree with prefixing `is` for properties that return a `Bool`.

**Comment by simonmika** [comment]
In a properly designed language there should not be any conflicts with having a static property and an instance property with the same name. As they are properties on two different things (object vs class) there are really no risk for misunderstandings. Some languages however are not designed well and therefore this issue arises.

I don't favor using `is` prefixes always but it might be the least bad thing to do in same cases.

**Comment by niklasborwell** [comment]
Agree with 
`identity` - returns new
`isIdentity` - return bool
Seems crystal clear to me.

**Comment by marcusnaslund** [comment]
We've reached a decision. Prefix with `is` and `has` whenever property returns `Bool`.
