### ISSUE TITLE
Rewrite BlockedQueue and SynchronizedQueue tests

### ISSUE THREAD

**Issue by sebastianbaginski** [cogneco/ooc-kean#489]
I think both tests should be rewritten. Currently they do almost the same thing (run `diff test/collections/BlockedQueueTest.ooc test/collections/SynchronizedQueueTest.ooc` to see what I'm talking about). Implement them properly to test each data structure instead of running five functions in a `ThreadPool`.

**Comment by sebastianbaginski** [comment]
Ok, so they use each data structure, I missed that in the diff output :P I think we should at least fix the random crashes.

**Comment by davidhesselbom** [comment]
> I think we should at least fix the random crashes.

Yes please
