### ISSUE TITLE
Promise/Future missing wait() with timeout

### ISSUE THREAD

**Issue by marcusnaslund** [cogneco/ooc-kean#498]
The classes `Promise` and `Future` currently only support blocking `wait()`. This makes it impossible to check whether an asynchrounous task has completed and do something else if it has not. We need something like `wait(timeout: Int) -> Bool` which returns the status within `timeout` milliseconds.

**Comment by marcusnaslund** [comment]
Waiting on #438

**Comment by marcusnaslund** [comment]
Will be resolved by #509 .

**Comment by davidhesselbom** [comment]
@emilwestergren Does this solve any of the things you mentioned before?

**Comment by emilwestergren** [comment]
No
