### ISSUE TITLE
Dissolve SDK into Kean

### ISSUE THREAD

**Issue by thomasfanell** [cogneco/ooc-kean#503]
The plan is to try to get rid of the SDK in its present form and to make it a natural part of Kean. Why? The current SDK is a mess, quite frankly.
* The memory management is in many cases non-existent (written with GC in mind).
* The coding standard (file/folder structure, naming convention, typographic style, etc) is a wild departure from our own, making it inconvenient to work with.
* Introducing Kean functionality into the SDK can be problematic and may cause circular dependency issues, thus limiting our ability to improve it.

Feedback/suggestions appreciated.

**Comment by davidhesselbom** [comment]
It would have to be done a piece at a time, but I agree the SDK is a mess in its current state.

**Comment by marcusnaslund** [comment]
A possible first step: #541

**Comment by marcusnaslund** [comment]
I understand this isn't a pressing issue, however:
- The `sdk/net` folder is not used at all (and never will be?) so it could be removed alltogether.
- We can also remove the `sdk/math` folder (note: not `math.ooc`) if we just alter line 199 in `sdk/structs/List.ooc`.
- The classes `sdk/structs/MultiMap.ooc` and `sdk/structs/Stick.ooc` are not used at all either and could be removed.
Is there a reason against starting to slim down the sdk part?

**Comment by davidhesselbom** [comment]
No, no reason at all. They're still there because we haven't made an effort to remove anything.

**Comment by davidhesselbom** [comment]
Still, before removing something, consider whether it could be useful to us or not. Just because we aren't currently using something doesn't mean we shouldn't or couldn't.

**Comment by thomasfanell** [comment]
I actually planned on keeping the network modules. I think every general library should have at least basic networking capabilities. If you want to get started with this, it's fine by me. I'm rather busy with other tasks at the moment anyway. Add yourself as an assignee if you want to join.

**Comment by marcusnaslund** [comment]
At least `Math/Random` is not neccessary since we have random generators now. I'll look into `MultiMap` and `Stick`.
@thomasfanell I would agree, but at the same time we're not doing anything connected (no pun intended) to that. But how about cleaning those files up and moving them to a new `source/networking` directory?

**Comment by thomasfanell** [comment]
Sounds good to me. :+1:

**Comment by marcusnaslund** [comment]
First steps: #555 and #557

**Comment by marcusnaslund** [comment]
This issue is too big, and since we've already made up our minds about this and started, I will be adding smaller issues related to SDK-minification as I move along.

**Comment by thomasfanell** [comment]
Great :+1:
