### ISSUE TITLE
The purpose of IntShell2D and FloatShell2D

### ISSUE THREAD

**Issue by marcusnaslund** [cogneco/ooc-kean#506]
`IntShell2D` and `FloatShell2D` seem to be very mildly used. Since we also have `IntBox2D` and `FloatBox2D`, is there a reason to also have the `Shell` versions? 

It seems that everything they can do could just as easily be handled with the `Box` variants instead, and a lot of the `Shell` functions already return `Box`es, not `Shell`s.

**Comment by davidhesselbom** [comment]
The purpose of these classes is to hold information about the padding between nested boxes. For instance, if you have a picture displayed on a canvas that is larger than the picture, `Shell` is used to describe the padding, and could be useful for e.g. making sure the picture does not move closer to the edge of the canvas than the padding allows. I'm not sure whether we actually have any use for it at the moment, but it's possible a box is currently being used for something that should have been a `Shell`.

**Comment by marcusnaslund** [comment]
Knowing that the code makes more sense. It's hard to tell without any documentation. Thanks.

**Comment by davidhesselbom** [comment]
I had the ambition at some point that all classes should have a brief description motivating their existence. I guess this issue proves that ambition still has some merit.

**Comment by marcusnaslund** [comment]
Totally agree. With more and more developers and an increasing code base, the lack of documentation is going to cause bigger questions/problems eventually.

**Comment by thomasfanell** [comment]
Proper documentation is a key requirement for any software project really. We should make an effort to document everything very soon, while the codebase is still relatively small. Code reading and program comprehension are by far the most time-consuming parts of software maintenance.

**Comment by davidhesselbom** [comment]
> the codebase is still relatively small

\*coughs\*

> Proper documentation is a key requirement for any successful software project really. We should make an effort to document everything very soon

The problem is, documentation easily becomes outdated, even the often meaningless XML junk interspersed in the code (see `FloatMatrix.ooc` for an example) which usually just makes people have to scroll a lot more. I think we should limit ourselves to documentation for anything that isn't obvious, but most of all, a brief description that explains the purpose of each class. We should absolutely not "document everything".

**Comment by marcusnaslund** [comment]
> We should absolutely not "document everything".

"Everything" can mean different things. I don't think @thomasfanell meant something like
```ooc
//uses println() to print "hello" to the user
println("hello")
```
I do agree we should document the purpose of each class (although I'm not sure 160 characters is always enough) _and_ every function whose purpose isn't semi-obvious.

**Comment by davidhesselbom** [comment]
That we can do. But we don't need to document every function, and we especially don't need to document it with XML bloat (just in case anyone had that in mind).

**Comment by marcusnaslund** [comment]
Speaking of which, should we remove the XML from `FloatMatrix`?

**Comment by thomasfanell** [comment]
@marcusnaslund Right you are. The golden rule of documentation is just that, to document things that are not immediately obvious. To document obvious code is a waste of time and space, I think everyone here is on board with that notion.

**Comment by davidhesselbom** [comment]
`lupDecomposition`, `solve`, `forwardSubstitution`, and `backwardSubstitution` all have meaningful comments in the XML, but we don't need the actual XML. The rest of the functions have useless comments, as far as I can see.
