### ISSUE TITLE
Rename `createGpuImage` method in AbstractContext

### ISSUE THREAD

**Issue by sebastianbaginski** [cogneco/ooc-kean#513]
This method is meant to return `GpuImage` in `GpuContext` and `RasterImage` in `CpuContext`.
Should it be simply called `createImage` ?

**Comment by davidhesselbom** [comment]
It definitely shouldn't be called `createGpuImage` and return a `RasterImage` (well, technically, `GpuImage` should inherit from `RasterImage`)...

**Comment by davidhesselbom** [comment]
I just realized this doesn't change anything, though. Even if `GpuImage` were to inherit from `RasterImage`, a function called `createGpuImage` should return a `GpuImage`.
