### ISSUE TITLE
Verify `open` method in RasterYuv420Semiplanar

### ISSUE THREAD

**Issue by sebastianbaginski** [cogneco/ooc-kean#522]
Add test cases and fix invalid memory reads

**Comment by davidhesselbom** [comment]
It *probably* only has problems with odd-sized images, but that's just a guess.

**Comment by sebastianbaginski** [comment]
@davidhesselbom you are right, no problems when size is even.
So the problem is in `convertFrom` method, with odd-sized images. It is really a weird one, which I only know how to workaround.
This code causes *valgrind* to report an *invalid read* warning:
```ooc
source := RasterBgr new(IntSize2D new(1, 1))
source[0,0] = ColorBgr new(0,0,0)
raster := RasterYuv420Semiplanar convertFrom(source)
```
originating from here
```ooc
	apply: func ~bgr (action: Func(ColorBgr)) {
		for (row in 0 .. this size height)
			for (pixel in 0 .. this size width) {
				pointer := this buffer pointer + pixel * this bytesPerPixel + row * this stride
				action((pointer as ColorBgr*)@)
			}
	}
```
I checked the buffer accesses, all addresses were within valid range (it is just one pixel, so it was possible to printout everything).
Here comes the weird part - it works without the invalid read warning if you do it like that instead:
```ooc
	apply: func ~bgr (action: Func(ColorBgr)) {
		for (row in 0 .. this size height)
			for (pixel in 0 .. this size width) {
				pointer := this buffer pointer + pixel * this bytesPerPixel + row * this stride
				color := (pointer as ColorBgr*)@
				action(color)
			}
	}
```
So, creating a temporary variable and passing it to the function disables the *invalid read* warning.
At that point I started to suspect that *rock* is doing something funny. So, I was surprised even more after I checked the generated C code:
```C
// code with the warning
                    ((void (*)(Color__ColorBgr, void*)) action.thunk)((*((((Color__ColorBgr*) (pointer))))), action.context);

// code without the warning
                    Color__ColorBgr color = (*((((Color__ColorBgr*) (pointer)))));
                    ((void (*)(Color__ColorBgr, void*)) action.thunk)(color, action.context);
```
It looks correct.
*Let's go deeper...* Here is generated assembly code (well, only the diff output, I won't paste a 1.7KLOC assembler source here):
```asm
// without the warning
	movq	-72(%rbp), %rdx
	movq	%rdx, %rsi
	movq	-48(%rbp), %rdi

// with warning
	movq	-72(%rbp), %rcx
	movq	-24(%rbp), %rdx
	movq	%rcx, %rsi
	movq	(%rdx), %rdi
```
The only difference is that `%rdi` register contains value at address `(%rbp-48)` in correct case, and `(%rbp-24)` in the *warning* case. So, in the *incorrect* case it tries to read from the address shifted a little too much from the base address. Don't ask me why.
Assembly output looks even more tricky when you generate it with `-O2` optimizations - it's been a while since I took the asm classes, so maybe I will skip that, I want to go home soon :D
Yes, so the workaround is to create a temporary variable like above, it makes all the warnings go away.
