### ISSUE TITLE
TimeSpan has no toString() function

### ISSUE THREAD

**Issue by davidhesselbom** [cogneco/ooc-kean#524]

**Comment by marcusnaslund** [comment]
Do we need it? And how? In as short form as possible, like `2 weeks, 3 hours, 7 milliseconds`?

**Comment by davidhesselbom** [comment]
I guess using a format string, as in `DateTime` would work.

**Comment by marcusnaslund** [comment]
Unless there are any objections, I'm doing this:
```ooc
// supported formatting expressions:
//	%w - weeks (rounded down)
//	%d - days (<7)
//	%h - hours (<24)
//	%m - minutes (<60)
//	%s - seconds (<60)
//	%z - milliseconds (<1000)

//	%D - days (based on total ticks)
//	%H - hours (based on total ticks)
//	%M - minutes (based on total ticks)
//	%S - seconds (based on total ticks)
//	%Z - milliseconds (based on total ticks)
```
Don't think any leading zero-versions are applicable here.

**Comment by davidhesselbom** [comment]
I'm inclined to agree. Will it print integer values, or can you get something like `1.53 s`?

**Comment by marcusnaslund** [comment]
No, because `TimeSpan` doesn't do that either (all functions return `Int64`).

**Comment by davidhesselbom** [comment]
Did we decide on anything final in #508? I'd like to do that before I merge this.
