### ISSUE TITLE
expect() calls should use "is equal to()" etc.

### ISSUE THREAD

**Issue by davidhesselbom** [cogneco/ooc-kean#527]
Many `expect` calls still compare values by using operators instead of constraints, e.g.
```ooc
expect(foo == bar)
```
instead of
```ooc
expect(foo, is equal to(bar))
```
The latter may seem clunkier but has the benefit that it can print the actual value of `foo`, should the comparison fail. This will only work for a few basic types (`String`, `Text`, and numeric types), so it can't be used for everything, but wherever it can be used, it should be.

**Comment by marcusnaslund** [comment]
Good point, I will keep this in mind as I'm going through all the tests.
