### ISSUE TITLE
Fixture does not handle Int64

### ISSUE THREAD

**Issue by marcusnaslund** [cogneco/ooc-kean#528]
Because the `TimeSpan elapsedDays()` (among others') return type is `Int64` it is not possible to do the following in a test:
```ooc
expect(span elapsedDays(), is equal to(1))
```
This gives an error like `expected equal to '24', was '24.00000000'`. This should be adressed. For now, the following workaround can be used:
```ooc
expect(span elapsedDays() as Int, is equal to(1))
```
The same may be true for other basic numeric types as well.

**Comment by davidhesselbom** [comment]
Your 2 code examples look identical to me...

**Comment by marcusnaslund** [comment]
Oops. Updated.
