### ISSUE TITLE
SVG plotting is not reusable enough

### ISSUE THREAD

**Issue by davidpiuva** [cogneco/ooc-kean#534]
Sometimes, I need drawing of time intervals and global statistical measurements. The simplest solution would be to just give draw calls directly to SvgWriter2D or PlotData2D since making a new plotter for each special case would require too much maintenance.

**Comment by davidhesselbom** [comment]
I agree, plotting requires tons of coding in general.

**Comment by davidpiuva** [comment]
Implemented and rejected by Simon.
