### ISSUE TITLE
Remove dependancy on math in ooc-collections

### ISSUE THREAD

**Issue by marcusnaslund** [cogneco/ooc-kean#541]
The only obstacle to moving `math.ooc` from the sdk into `ooc-math` is the use of `Range` in `ooc-collections`. Because `ooc-math` has a dependancy on `ooc-collections`, we would otherwise get a circular dependancy. The `Range` cover is extended in `math.ooc`.

If we could accomplish this, we "never" need to have `import math` in any file, only `use ooc-math`.

**Comment by davidhesselbom** [comment]
The `Range` extension could be moved into `lang/Types` where `Range` is defined, but it uses `Int clamp`, which is also defined in `math.ooc`...

**Comment by sebastianbaginski** [comment]
Maybe you could hard-code the uses of `Int clamp` this one time ?:) By hard-code I mean inline it manually

**Comment by davidhesselbom** [comment]
Might have to, yeah. It just bothers me, this whole dependency thing...

**Comment by marcusnaslund** [comment]
Well this can be done, because I just did it. :)
All the kean tests build and run, **but** I get a thousand or so warnings of the type `incompatible implicit declaration of built-in function ‘sqrt’` because rock throws in stuff like
```c
#define Extensions__sqrt sqrt
```
after moving all the extensions to a file in `ooc-math` called `Extensions.ooc`. It seems like rock does something special for definitions in the sdk..?

**Comment by marcusnaslund** [comment]
This is pretty easy to do now. Question is, do we really want `math.ooc` in `source/math`, or should it stay in the `sdk`? @simonmika ?

**Comment by simonmika** [comment]
I think that basic operations on `float`, `int`, etc could stay in the sdk but the other option is also viable. Any suggestions? @fredrikbryntesson @thomasfanell @sebastianbaginski @marcusnaslund ?

**Comment by sebastianbaginski** [comment]
For me everything that solves the weird
```ooc
use ooc-math
import math
```
is good enough.

**Comment by thomasfanell** [comment]
I would like to see the `sdk` folder disappear from `ooc-kean`, since `ooc-kean` is our real SDK. But, if that is not feasible in the foreseeable future, then basic operations that act on "built-in" types should stay in `sdk`.

**Comment by simonmika** [comment]
I suggest the following long term vision:

- [ ] Remove `ooc-` from use file names in kean.
- [ ] Rename `sdk` to `system`.
- [ ] Stop importing the `sdk` but instead having `use system` explicitly in like every source file.
- [ ] Have the extensions on the basic numeric value types in `system`.

What do you think?

**Comment by marcusnaslund** [comment]
I would rather see us having everything in `system` imported by default like it is now with certain parts of the `sdk`.

**Comment by simonmika** [comment]
That is an option. The drawback is that it convolutes the name space i.e. nobody can ever have a class called `Buffer`.

**Comment by marcusnaslund** [comment]
> The drawback is that it convolutes the name space i.e. nobody can ever have a class called Buffer.

I don't know, I think that's a good thing, to avoid confusion. "Hey, why isn't this `Buffer` instance behaving the way I know `Buffer` should? ... ... ... Oh, it's not the system `Buffer` class."

**Comment by simonmika** [comment]
I would prefer the name `system Buffer` or something.

**Comment by marcusnaslund** [comment]
Adding `Imports: math` to `sdk.use` gets rid of `import math` everywhere. On it.

**Comment by marcusnaslund** [comment]
Since we're keeping `math.ooc` inside the sdk, this issue can be closed.
