### ISSUE TITLE
Box needs resize functions

### ISSUE THREAD

**Issue by davidhesselbom** [cogneco/ooc-kean#551]
Changing the size of an existing `IntBox` or `FloatBox` without moving its center is currently too complicated - they need functions for making this easier.

**Comment by marcusnaslund** [comment]
Hmm, we have some `pad` functions, but they return a new `Box`. `FloatBox` also has `shrink` which also creates something new.
Do you mean something like
```ooc
resize: func (leftChange, topChange, rightChange, bottomChange: Float) {
//...
}
```
?

**Comment by davidhesselbom** [comment]
Technically, I guess I want a function that returns a new box rather than creates a new one. Specifically, I want functions for creating a new box with `this center` as the new center and
- a specified size 
- a scale factor (that only affect size, not position)
- a size that is at least as large as the `Size` passed to the function (if the box is already larger, it remains unchanged)
- a size that is no larger than the `Size` passed to the function (if the box is already smaller, it remains unchanged)

**Comment by davidhesselbom** [comment]
Also, a function that creates a new box with `this center` as its center and `Size new(this width + this height, this width + this height)` as its size.

**Comment by marcusnaslund** [comment]
> returns a new box rather than creates a new one

What?

**Comment by davidhesselbom** [comment]
Lol, sorry. Edited.

**Comment by marcusnaslund** [comment]
Alright, I can fix this.
