### ISSUE TITLE
Optimize task synchronization with conditions

### ISSUE THREAD

**Issue by emilwestergren** [cogneco/ooc-kean#554]
The current implementation of `wait` for Task is based on an inefficient busy-waiting loop (sleep 1 ms, check if done, sleep 1 ms, check if done... etc). This means that on average threads wait for 0.5 ms too long (worst case 1 ms) when synchronizing with tasks and also cause unnecessary overhead (context switch, mutex lock/unlock, polling of the task...) every time this check is made.

A better solution for this is to use WaitConditions. If the cost of allocating a WaitCondition for every task is too high then we could recycle these instead.

**Comment by marcusnaslund** [comment]
I also believe this would be better, but isn't/wasn't there a lot of debate on this?

**Comment by davidhesselbom** [comment]
Yes, but now we know for a fact that the new solution is slower than what we had.

**Comment by emilwestergren** [comment]
I have already fixed this. I'm doing some profiling to make sure it really is faster.
