### ISSUE TITLE
Plenty of TODO and FIXME in Raster* classes

### ISSUE THREAD

**Issue by marcusnaslund** [cogneco/ooc-kean#561]
Most of the `TODO`s and `FIXME`s in kean are in the `Raster*` classes such as `RasterMonochrome`, `RasterYuv420SemiPlanar` etc.

These are mostly related to commented-out sections of code or whole functions.

- Do we (still) need/want them?
- Are there ways to improve what's there?
- Do we now know how to solve these problems?

I'm making this issue so that this doesn't go unnoticed forever.

**Comment by davidhesselbom** [comment]
Can't give you an answer that covers all the cases, but many of them can probably be removed, and other can be fixed. For instance, in `RasterMonochrome` (and other related classes) `open`, memory is copied unnecessarily:

```ooc
		buffer := ByteBuffer new(x * y * requiredComponents)
		// FIXME: Find a better way to do this using Dispose() or something
		memcpy(buffer pointer, data, x * y * requiredComponents)
		StbImage free(data)
```

This isn't a high priority, but it would be nice to get it fixed, and it deserves a `FIXME` until it is indeed fixed.

**Comment by davidhesselbom** [comment]
```ooc
//	FIXME
//	openResource(assembly: ???, name: String) {
//		Image openResource
//	}
```
can be removed, everywhere.

**Comment by marcusnaslund** [comment]
All `openResource` FIXMEs removed with #563

**Comment by davidhesselbom** [comment]
Great. Btw, all `StbImage free` does under the hood is `free(data)`, so fixing that needless copy should be a piece of cake:
```ooc
buffer := ByteBuffer new(data, x * y * requiredComponents)
```
instead of 
```ooc
		buffer := ByteBuffer new(x * y * requiredComponents)
		// FIXME: Find a better way to do this using Dispose() or something
		memcpy(buffer pointer, data, x * y * requiredComponents)
		StbImage free(data)
```

**Comment by davidhesselbom** [comment]
While you're at it, `requiredComponents` can be replaced by `this bytesPerPixel`, and boom, the function can be made identical for nearly all `RasterPacked` classes...

**Comment by marcusnaslund** [comment]
Awesome. How about the recurring
```ooc
//		else if (!other instanceOf?(This))
//			FIXME
//		else if (this size != other size)
//			FIXME
```
in `distance()`?

**Comment by sebastianbaginski** [comment]
I think in the first case we should do the comparison anyway (convert the other to `This` and call `distance()`).
Second case I'm not sure, resize and compare ? But which one ?

**Comment by marcusnaslund** [comment]
@davidhesselbom Actually since `open` is static I cannot call `this bytesPerPixel` but we could probably solve that in some other way.

**Comment by davidhesselbom** [comment]
Can `bytesPerPixel` be made static, then?

**Comment by marcusnaslund** [comment]
Why a property and not a static constant?

**Comment by davidhesselbom** [comment]
Well...  is there such a thing as a "constant" in ooc?

**Comment by marcusnaslund** [comment]
Yes, the `const` keyword is parsed by rock.
No, rock throws the `const` keyword out without doing anything.
Property it is.

**Comment by davidhesselbom** [comment]
Sorry :/ I do think you can make a static property though...

**Comment by marcusnaslund** [comment]
I believe so too, but there is so much inheritance and other stuff going on in these classes I want to be careful I don't break anything. It's coming, though.

**Comment by davidhesselbom** [comment]
Well, it's a good thing we have all these tests... :)

**Comment by marcusnaslund** [comment]
Making `bytesPerPixel` static compiles but gives me:
```RasterYuv420Semiplanar *** Error in `./Tests': double free or corruption (out): 0x0000000001ed01a0 ***```
And this class doesn't even use `bytesPerPixel`. I need to look into this some more or just leave `requiredComponents` as-is.
Do you know about `shift()` in `RasterPacked? It's all commented out.

**Comment by davidhesselbom** [comment]
It's probably not implemented correctly. Most of the `Raster` classes were converted from C#. I don't think we're using `shift`...

**Comment by marcusnaslund** [comment]
Hm, `open` in `RasterImage` seems to use local variable `n` in the same way we use `requiredComponents` in the derived classes. I tried to dig down into `StbImage` which sets the value of `n` but got completely lost. Do you know anything about this?

**Comment by sebastianbaginski** [comment]
For example when you open png images, `n` is set in `stb__do_png`: `if (n) *n = p->s->img_n;`
It just sets `n` to the number of bytes per pixel, which is defined in the image file data. Then `RasterImage` tries to match it to one of our classes (1 - single channel monochrome, 3 - blue, green, red, 4 - blue, green, red, alpha).

**Comment by marcusnaslund** [comment]
@sebastianbaginski But then `n` is exactly the same as `requiredComponents`?

**Comment by sebastianbaginski** [comment]
Not always. `n` is always set to the number of channels in the image file, while `requiredComponents` is the number of components you want to load. You can set `requiredComponents = 3` and load BGRA data just fine (and then `n` would be set to `4`).

**Comment by davidhesselbom** [comment]
Clearly, the variable needs a better name :-)

**Comment by marcusnaslund** [comment]
Ah, alright, I understand now.

**Comment by marcusnaslund** [comment]
From `RasterYuv422Semipacked`:
```ooc
// TODO: What does this function even do?
```
This seems like a strange "todo".

**Comment by davidhesselbom** [comment]
Yes, I probably didn't know about `FIXME` at the time. I was using gedit, and it highlights those two words (and I think it has a plugin that allows you to find them all, too).

**Comment by marcusnaslund** [comment]
But it's also a strange "fixme", I mean, there's nothing to fix or do. It's just a question.
We never use this function, by the way.

**Comment by davidhesselbom** [comment]
Right, but there's no `QUESTION` keyword. I guess it could have said `TODO: Figure out what this function does and whether to remove it`.

> We never use this function, by the way. 

That's probably why the comment is still there... :P

**Comment by marcusnaslund** [comment]
> I guess it could have said `TODO: Figure out what this function does and whether to remove it`

That's what it will say from now on. :)
