### ISSUE TITLE
FloatConvexHull2D does not actually compute the convex hull

### ISSUE THREAD

**Issue by marcusnaslund** [cogneco/ooc-kean#562]
The constructor merely sets the given points (which are hopefully a convex set), and applying a transformation does not recompute the convex hull either, as it should.

There is also a limitaton mentioned that `// Points must be in clockwise order` - we might also want to take care of this.

**Comment by davidhesselbom** [comment]
Should this go in the `bugs` milestone, perhaps?

**Comment by marcusnaslund** [comment]
It depends - we are not using it in a manner which expects the class to compute the convex hull, but there are `TODO`s saying it should. It's definitely something that should (and would) have been fixed before a PR today.

**Comment by davidhesselbom** [comment]
Alright.
