### ISSUE TITLE
CsvReader does not handle multi-line string literals

### ISSUE THREAD

**Issue by marcusnaslund** [cogneco/ooc-kean#566]
There's a `TODO` in the file saying it should.
This issue is here so that it isn't forgotten.

**Comment by thomasfanell** [comment]
Do we need multi-line literal support?

**Comment by marcusnaslund** [comment]
You put that TODO there so I was hoping you would know. :)

**Comment by thomasfanell** [comment]
I can't think of a real scenario where we would need it actually.

**Comment by marcusnaslund** [comment]
If not, remove the todo :)

**Comment by thomasfanell** [comment]
... hence my question here ...

**Comment by marcusnaslund** [comment]
Noone has said anything about this in two weeks, so, I guess we remove it and close this?

**Comment by thomasfanell** [comment]
I think it's safe to close this for now, since we don't need that feature right now. I will get around to it someday though, it's in the back of my head.
