### ISSUE TITLE
Parse methods in math use String and ArrayList

### ISSUE THREAD

**Issue by marcusnaslund** [cogneco/ooc-kean#569]
A lot of `math` classes (like `FloatPoint`, `FloatSize`, `IntPoint`, etc.) have a `static parse` method which takes a `String` argument. These methods call `split` on the input which returns an `ArrayList`.

Since we want to move away from both `String` and `ArrayList`, shouldn't `parse()` move on to take arguments of `Text` instead? Then `split` would return a `VectorList` which is more easily cleaned up. Right now, most of the `parse` methods leak memory.

**Comment by davidhesselbom** [comment]
Yes, now that we have `Text`, this is what we should be doing.

**Comment by marcusnaslund** [comment]
There is a discrepancy sometimes between what `parse` expects (usually, separated by `' '`) and what `toString()` outputs (usually separated by `', '`, adding an `i` at the end etc.)
I will leave it as it is, but this is perhaps something to look at later?

**Comment by davidhesselbom** [comment]
The `parse` function should agree with the `toString` function, yes. Sounds like a separate issue though.
