### ISSUE TITLE
rock tries to resolve enum values inside versioned-out blocks

### ISSUE THREAD

**Issue by sebastianbaginski** [cogneco/ooc-kean#572]
```ooc
version(windows) {
include windows
TestEnum: enum {
	Symbol1 = WAIT_OBJECT_0
}
}

```

> rock_tmp/ooc/enums/enums.c: In function ‘enums_load’:
> rock_tmp/ooc/enums/enums.c : 100:13: error: ‘WAIT_OBJECT_0’ undeclared (first use in this function)
>             WAIT_OBJECT_0
>             ^
>rock_tmp/ooc/enums/enums.c : 100:13: note: each undeclared identifier is reported only once for >each function it appears in

this won't compile on Unix as rock tries to resolve the value of `Symbol1`, even though everything is inside version block specific to Windows.
This is very bad, because in `x11.ooc` file there are two enum types specific to x11, which are causing compilation failure on Windows.
Now there is no version block around these (pull request coming up), but it fails even when entire x11.ooc file is inside version block.

**Comment by davidhesselbom** [comment]
Can you please try this again with the official version of rock make an identical issue in https://github.com/fasterthanlime/rock?

**Comment by sebastianbaginski** [comment]
I will do that, I'm fetching the latest rock now.

**Comment by davidhesselbom** [comment]
Actually, leave out the `x11` if you do make an issue in rock - it's not relevant, after all.

**Comment by sebastianbaginski** [comment]
Sure.

**Comment by sebastianbaginski** [comment]
Done: https://github.com/fasterthanlime/rock/issues/935

**Comment by davidhesselbom** [comment]
Thanks. I don't think this is unique to enums, unfortunately. It seems rock parses everything first and then makes a decision about whether it should be compiled or not.

**Comment by sebastianbaginski** [comment]
Yes, it is not specific to enums.

**Comment by sebastianbaginski** [comment]
One workaround could be to move every symbol out of the enum, declare it as Int or something and then define missing symbols for other versions. This one works:
```ooc
Symbol1: Int

version(unix){
WAIT_OBJECT_0 := 0
}

version(windows) {
include windows
Symbol1 = WAIT_OBJECT_0
}

```
It kinda does what we want - on windows define a `Symbol1` with value `WAIT_OBJECT_0`, but it also introduces extra unused symbols on unix.
I don't know how we should solve this.

**Comment by davidhesselbom** [comment]
Me either. I'm surprised this hasn't been fixed earlier, since there's lots of platform dependent code in the sdk...

**Comment by sebastianbaginski** [comment]
This would also work:
```ooc
version(windows) {
include windows
	Symbol1: extern (WAIT_OBJECT_0) Long
}

```

**Comment by sebastianbaginski** [comment]
```ooc
version(windows) {
include windows
	TestEnum : class {
	Symbol1: static extern (WAIT_OBJECT_0) Long
	}
}
```
This one compiles on Unix. I will try to update the x11 file like that.

**Comment by davidhesselbom** [comment]
Good enough for me. I'm glad that's all it took!

**Comment by sebastianbaginski** [comment]
https://github.com/cogneco/ooc-kean/pull/573 contains a workaround for this problem.

**Comment by sebastianbaginski** [comment]
Should we keep this open ? https://github.com/cogneco/ooc-kean/pull/573 was merged and this one does not affect us any more. For now.

**Comment by davidhesselbom** [comment]
I guess we can close it. Leave the one in rock open, though.
