### ISSUE TITLE
Sorted VectorList

### ISSUE THREAD

**Issue by marcusnaslund** [cogneco/ooc-kean#596]
So, `source/collections/SortedVectorList.ooc` is basically a file with a really long comment, and hasn't been updated for eight months. I'm guessing it's not working because of problems with rock concerning generic types and generic comparator functions.
Do we want it? Remove it?

**Comment by davidhesselbom** [comment]
I don't remember what we were even supposed to use it for. @simonmika ?

**Comment by marcusnaslund** [comment]
Note: There is also a generic `sort` function in `VectorList` which I guess is meant to do the same thing, but also doesn't work because of the same problems.

**Comment by simonmika** [comment]
I would very much like to have a list that always stays sorted but if it does not work, kill it for now.

**Comment by marcusnaslund** [comment]
No, it's very unfinished.

**Comment by simonmika** [comment]
Kill it.
