### ISSUE TITLE
FloatBox2D pad(Float)

### ISSUE THREAD

**Issue by davidhesselbom** [cogneco/ooc-kean#599]
There are two functions with the same signature in `FloatBox2D` (and possibly elsewhere, too):
```ooc
	pad: func ~fromFloat (pad: Float) -> This { this pad(pad, pad, pad, pad) }

	pad: func ~fraction (pad: Float) -> This {
		this pad(pad * this size / 2.0f)
	}
```
Evidently, these two functions don't do that same thing, but both can be called like `pad(myFloat)`, which means we don't know which one of them is actually called. This is not good.

Rename one of these functions to resolve the ambiguity, but first, find every place `pad` is called and figure out which one of them is actually being called in the C code.

@thomasfanell, is there any way we can make magic detect this (functions that have a "twin" with the same name and the same signature in the same namespace)? It should be rock's job, really, but since it doesn't do its job, someone else will have to.

**Comment by marcusnaslund** [comment]
Even more funny, the second `pad` calls `this pad()` with the argument called `pad`. What a mess.

**Comment by davidhesselbom** [comment]
Haha, yes.

**Comment by davidhesselbom** [comment]
For reference: https://github.com/cogneco/Kean/blob/develop/Kean/Math/Geometry2D/Single/Box.cs

**Comment by marcusnaslund** [comment]
There is only one use of `pad` without suffix and it is supposed to be `pad~float` according to @niklasborwell 
I guess we should rename `pad~fraction`. Judging by the test it's the opposite of `shrink`, so something like `enlarge()` or `extend()` or `stretch()`(?) is probably better. What do you think?

**Comment by marcusnaslund** [comment]
Related: We have
```ooc
shrink: func ~fraction (margin: Float) -> This {
	this pad(-margin * this height / 2.0f)
}
```
Shouldn't it be `this size` instead of `this height`, as in `pad~fraction`?

**Comment by davidhesselbom** [comment]
Probably...
