### ISSUE TITLE
Half-perimeter of a rectangle

### ISSUE THREAD

**Issue by davidhesselbom** [cogneco/ooc-kean#600]
In a bunch of places, we use the sum of a box's width and height to compute various things. Is there a term for this? 

The perimeter of a rectangle is `2 * (width + height)` so our sum is the half-perimeter, but that's a pretty long name for something so simple. 

Anyone?

**Comment by marcusnaslund** [comment]
From wikipedia: `In geometry, the semiperimeter of a polygon is half its perimeter. `
https://en.wikipedia.org/wiki/Semiperimeter

**Comment by davidhesselbom** [comment]
Not a lot better, but at least there's an "official" term. Thanks.
