### ISSUE TITLE
IntTransform2D is feeling lonely

### ISSUE THREAD

**Issue by marcusnaslund** [cogneco/ooc-kean#602]
Right now, there is no test for `IntTransform2D`. Before I go and create one, I would like to make sure we need it. Right now, we are not using this class (cover) at all, and we never have.

**Comment by davidhesselbom** [comment]
I very much doubt we will ever need this for anything. @simonmika ?

**Comment by simonmika** [comment]
We probably don't need it. In C# we generated it from the same template as single and double but I doubt we ever used it.

**Comment by marcusnaslund** [comment]
Hmm I take that back, must have not searched everywhere. We do use `IntTransform2D` in in a few places in the OpenGL code. In a very limited way though, only to create the identity transform with possibly one element as `-1`.
Then we do stuff like `this transform toFloatTransform2D()` in `RasterImage copy()` anyway. Is there a performance benefit I'm missing?
Who knows about this? @ziquanyu ?

**Comment by davidhesselbom** [comment]
More likely @emilwestergren ...

**Comment by emilwestergren** [comment]
Every Image has it: `transform: IntTransform2D { get set }`. It is used to define the coordinate system of the Image. This is useful in OpenGL to know how to flip the Image correctly.

**Comment by emilwestergren** [comment]
I wouldn't really care if it was a FloatTransform2D instead though.

**Comment by marcusnaslund** [comment]
If it doesn't matter which, I'd vote to get rid of the int version then.

**Comment by simonmika** [comment]
Keep it. It works and replacing it will reduce performance as pushing things between the ALU and the FPU can be very expensive on at least some ARM processors.

**Comment by marcusnaslund** [comment]
I will write a test, then.

**Comment by davidhesselbom** [comment]
> Keep it. It works and replacing it will reduce performance as pushing things between the ALU and the FPU can be very expensive on at least some ARM processors.

Keeping it also means maintaining something we don't use. Or are you saying we should start avoiding `Int`<->`Float` conversions altogether? We have a lot to work on, in that case.
