### ISSUE TITLE
Timestamps and run time for finished tests

### ISSUE THREAD

**Issue by davidhesselbom** [cogneco/ooc-kean#603]
Some tests take a long time on the build servers, and it would be nice to have `Fixture`s report their start time when they start and run time when they complete, so you can get an idea of how long each test takes without watching it happen.

**Comment by marcusnaslund** [comment]
Printing the run time I think is a great idea, but

> report their start time when they start

As in the current time? What does that information bring us?

**Comment by marcusnaslund** [comment]
Is this too messy?
```
TimeSpan ....... done (runtime=0.00 s, total=18.88 s)
ReferenceCounter .. done (runtime=0.01 s, total=18.89 s)
Promise .. done (runtime=2.88 s, total=21.76 s)
TextBuilder ...... done (runtime=0.00 s, total=21.76 s)
ThreadPool .... done (runtime=4.98 s, total=26.74 s)
```

**Comment by sebastianbaginski** [comment]
Maybe without the `runtime=` and `total=` strings ? 
```ooc
TimeSpan ....... done (0.00 s, 18.88 s)
ReferenceCounter .. done (0.01 s, 18.89 s)
...
```

**Comment by marcusnaslund** [comment]
Yeah, we can skip `runtime=` anyway. Maybe `total=` also.

**Comment by davidhesselbom** [comment]
> As in the current time? What does that information bring us?

If the test is still running, that time stamp tells us for how long a test has been running and so, perhaps, whether it's time to abort the build.

**Comment by davidhesselbom** [comment]
The printouts result in a pretty messy output compared to earlier. Would it be possible to version out the timestamps, or (even better) align them so that they always start printing at the same column?

**Comment by marcusnaslund** [comment]
Aligning them should be easy, I'll try that

**Comment by marcusnaslund** [comment]
This will require updating a constant `maxOffset` in `Fixture` if in the future there are "too many" tests somewhere. The alternative is printing done/failed and the timings on a new line.

**Comment by davidhesselbom** [comment]
How many is "too many"? You mean enough to make the printout spill over into two lines? Seems unlikely.

**Comment by davidhesselbom** [comment]
And even if they do, the result would still be aligned...

**Comment by marcusnaslund** [comment]
Each `Fixture` instance knows only about its own test name and number of tests for that file. How could I calculate the maximum length of name + number of tests without hard-coding a value?

**Comment by davidhesselbom** [comment]
Oh, that's what you mean. Well, I *did* say it would be tricky :) The way `test.sh` currently works, I don't think there's a way.

**Comment by marcusnaslund** [comment]
Haha yes. Is hard-coding it too terrible?

**Comment by davidhesselbom** [comment]
One way, but one that will break the ability to run tests without `test.sh`, would be to remove the `run()` call from the test file itself and let `test.sh` add a call that runs all of the `Fixture`s added to the static list I mentioned earlier.

**Comment by marcusnaslund** [comment]
> break the ability to run tests without test.sh

Yeah, but that doesn't sound good at all.

**Comment by davidhesselbom** [comment]
Right.

**Comment by davidhesselbom** [comment]
So the script could, maybe, extract the `run` calls and put them last in the generated file. Shouldn't be too hard... but, still, another fix is to just allow the timestamps to be turned off.

**Comment by marcusnaslund** [comment]
Or, we could just print a timestamp (with/without milliseconds). All the other information can be inferred from there.

**Comment by sebastianbaginski** [comment]
Not related to this, but maybe you have a better idea on how to make the failed test case really stand out from every other printout ? Can you like make it print an additional new line or **"YOUR FAILED TEST IS UP HERE ^^^"** kind of message.
Sometimes I check the failure reason on AppVeyour and it is quite hard to find the failing Vector2D test :D

**Comment by marcusnaslund** [comment]
@sebastianbaginski I have had that problem many times myself. Since it's not, as you say, related, make a separate issue about it.

**Comment by davidhesselbom** [comment]
It is possible to change the color of the output, but it probably doesn't work the same way in both AppVeyor/Windows (Powershell?) and Linux/Circle CI.

**Comment by sebastianbaginski** [comment]
https://github.com/cogneco/ooc-kean/issues/671

**Comment by sebastianbaginski** [comment]
@marcusnaslund can we close this ?

**Comment by marcusnaslund** [comment]
I believe so. Don't think it's worth spending the time (heh) to try to align the time printouts.
