### ISSUE TITLE
Always free parameters and calling object in classes using OwnedBuffer backend

### ISSUE THREAD

**Issue by tomasmahlberg** [cogneco/ooc-kean#605]
The new backend `OwnedBuffer` is used in `FloatMatrix` and `Text` (implicitly via `TextBuffer`). The purpose of this backend is to simplify freeing. Right now, the general rule is that methods and operators that have return type `This` frees (with criterion) the calling object and parameters. Potentially, we also want properties and other operators, such as the subscript operator, to follow this behaviour.

**Comment by marcusnaslund** [comment]
Properties in `FloatMatrix` and `TextBuffer` (the only ones using `OwnedBuffer` at the moment) seem to follow this behaviour. Is there more left to do here?

**Comment by tomasmahlberg** [comment]
I think this was essentially fixed by #743 so I'll close this.
