### ISSUE TITLE
Evaluate performance of Quaternion weightedMean

### ISSUE THREAD

**Issue by tomasmahlberg** [cogneco/ooc-kean#617]
The performance of the static function `weightedMean` in `Quaternion` needs to be evaluated and eventual optimizations should be made. Right now it uses `FloatMatrix` operations which could potentially be replaced by nested for loops. It should be evaluated if it would be worth sacrificing readability of the code if the performance is noticeably better.

**Comment by davidhesselbom** [comment]
At the very least, remove some unnecessary computations in `_approximateMaximumEigenvalueForQuest`. `vectorQuantityZ transpose()` is computed 3 times, `matrixQuantityS * vectorQuantityZ` twice.

**Comment by tomasmahlberg** [comment]
I agree with you. The reason for only accessing the element at `[0, 0]` of `temporary` though is because we are essentially calculating the inner product of two vectors (a scalar) so the return value is a 1x1 `FloatMatrix` which we want to use as a `Float`. Again, we might be better off just using a simple for loop for this particular trivial calculation.

**Comment by davidhesselbom** [comment]
In that case, it's not as big a problem. I thought you were computing a new matrix or vector only to throw most of it away. Hm. Well, you could also make a function in `FloatMatrix` that computes the scalar product of 2 vectors...
