### ISSUE TITLE
CLIParser test is not implemented

### ISSUE THREAD

**Issue by marcusnaslund** [cogneco/ooc-kean#618]
The `CliParserTest` is right now completely commented out because the plan is to have a `main` function be called from a separate script, but it "it collides with main() in the generated test".

However, what we really want is to test the parser itself, not whether we can retrieve something from the commandline (which I suppose we can assume is always possible). So why not have some predetermined strings call a `CLIParser` instance and see what it comes up with?

**Comment by marcusnaslund** [comment]
@jonathanudd You're new argument parser in #737 means we close this, right?

**Comment by jonathanudd** [comment]
Yes I think so.
