### ISSUE TITLE
Some tests are for manual inspection - and should not always be run?

### ISSUE THREAD

**Issue by marcusnaslund** [cogneco/ooc-kean#620]
We have some tests such as `ProfilingTest`, `CLIParserTest`, `DebugPrintTest` etc. which print out stuff like:
```
ProfilingTest [TODO: Not implemented as a fixture!]
```
This text was put there to remind us that these tests need to be updated. Some of these, for example `CLIParserTest`, can be automated and rewritten as a `Fixture` instance. (which has now been done for `ArgumentParser`)

Others, like `DebugPrintTest`, `SvgPlotTest` etc. are tests which rely on manual inspection and **cannot** be written as automated tests. For those tests, I propose we introduce a flag (or rather use the `debugTests` which already exists for tests that do printouts/files - meaning they require manual inspection), and do the above printout "not implemented as a fixture", or something else, inside the version block.

Input is welcome.

**Comment by marcusnaslund** [comment]
@davidhesselbom @simonmika - input please.

**Comment by davidhesselbom** [comment]
Some of the things that "require manual inspection" (like `SvgPlotTest`) can probably be made automatable by comparing the output to a pre-made, committed reference output.

**Comment by simonmika** [comment]
Remove the TODO outputs, they just clog up the output. And while you are at it remove the timing printouts. They should be behind some version flag.

**Comment by marcusnaslund** [comment]
I'm putting this in cleanup then.
