### ISSUE TITLE
isNumber

### ISSUE THREAD

**Issue by davidhesselbom** [cogneco/ooc-kean#626]
Sometimes, we want to check that a floating point number isn't `NaN`. We do this by comparing the number to itself: if `value != value`, then `value` is `NaN`.

A property can be defined make this a little prettier:
`isNumber ::= this == this`

With it, the following program
```ooc
value := 0.0f
value isNumber toString() println()
value /= value
value isNumber toString() println()
```
prints 
```
true
false
```
But where should the function be added? 
- To `Numbers.ooc` (where it will always be available), or 
- to `math.ooc` (which will require anyone who wants to use it to `import math`)?

**Comment by davidpiuva** [comment]
Both ways works for me.

**Comment by niklasborwell** [comment]
@marcusnaslund Are we doing this?

**Comment by marcusnaslund** [comment]
Yes, I think this is a good idea.
