### ISSUE TITLE
Cleanup global variables and functions in Exception / Backtrace

### ISSUE THREAD

**Issue by sebastianbaginski** [cogneco/ooc-kean#630]
https://github.com/cogneco/ooc-kean/pull/627

**Comment by sebastianbaginski** [comment]
@davidhesselbom what do you think, should I fix the horrible formatting in these files too ?

**Comment by davidhesselbom** [comment]
Been a while since we gave up on keeping the SDK as-is, so go ahead, if you want to. Try not to break anything, though :)
