### ISSUE TITLE
Image TransformMethod

### ISSUE THREAD

**Issue by davidhesselbom** [cogneco/ooc-kean#641]
`Image` has an enum for 2 types of interpolation. This enum is only used by `RasterImage` for resizing images on the CPU, currently, and the name should probably `InterpolationMethod` or similar.

Also, to quote @emilwestergren,
> we need to decide if this should be a state for the Image or a parameter. Currently for GpuImages, filtering is a state for the Image that is being drawn (sampled). The good thing about this is that you don't have to supply it as a parameter and it also handles the case with draw calls where you have multiple images as input (for example in a shader) and only some of them should use bilinear filtering. Also, in this specific case there would be no need for an overloaded `resizeTo`.

**Comment by sebastianbaginski** [comment]
Filtering mode for GPU is good argument for the `mode` as internal state of the image.
One downside of such solution is that you will have to modify the image object itself just to resize it with different interpolation. It could be a problem when using multiple threads. I know that currently threads are not used heavily, but it's *not that hard to imagine* having to create, let's say, 4 rescaled copies of the same image, with smaller size each. There could be one thread resizing the image with bilinear method for the first level to get better quality, while second thread resizes the same image data faster, using linear sampling for next levels. Easier to do if the image data and interpolation mode are kept separately.
About the name, maybe `InterpolationMode` ?

**Comment by emilwestergren** [comment]
That's a good point, but there are other non-thread-safe states in Image already (like crop and wrap), so it would not be consistent unless we remove all of them. I like the idea of making the abstract Image class thread-safe, and in the end it's down to the implementation to maintain it or not.

**Comment by niklasborwell** [comment]
Fixed.
