### ISSUE TITLE
Shlex, Regexp, MultiMap, Stick, and others from the SDK: Keep or remove?

### ISSUE THREAD

**Issue by marcusnaslund** [cogneco/ooc-kean#647]
We have the following classes:

- `sdk/text/Shlex.ooc`
- `sdk/text/Regexp.ooc`
- `sdk/text/StringTemplate.ooc`
- `sdk/structs/MultiMap.ooc`
- `sdk/structs/Stick.ooc` 

We don't use them, and neither does the SDK.

They should either (1) be cleaned up, become magic-compliant, lifted out of the SDK, and have tests written, or (2) removed completely.

Regexp seems like a good thing to have (but not sure it works? It needs `pcre.h` which doesn't exist), the others we can probably get rid of.

**Comment by marcusnaslund** [comment]
`Regexp` will be gone, it doesn't work. #655

**Comment by marcusnaslund** [comment]
After talking to @simonmika we're getting rid of `MultiMap` and `Stick` as well. #656 
Thoughts on `Shlex` and `StringTemplate`?

**Comment by davidhesselbom** [comment]
I'll have to take a look, but they can probably go, too.
