### ISSUE TITLE
No backtrace extension

### ISSUE THREAD

**Issue by marcusnaslund** [cogneco/ooc-kean#651]
With the inclusion of the `ExceptionTest` we now get a hundred-or-so lines of 
```
[lang/Backtrace] No backtrace extension nor execinfo - use a debugger!
```
when running the tests on CircleCI or Windows (including AppVeyor). It all still works fine, but it makes the output a lot more messy. Is there a way to actually fix this, or can (rather, *should*) we suppress this message?

**Comment by marcusnaslund** [comment]
According to this
https://github.com/fasterthanlime/rock/tree/master/extensions/fancy-backtrace
it should be easy enough to fix.

**Comment by marcusnaslund** [comment]
@fredrikbryntesson or @thomasfanell - do you know any more about this?

**Comment by marcusnaslund** [comment]
Hm, @jonathanudd , did you `make extension` when building rock for windows?

**Comment by jonathanudd** [comment]
I tried to run `make extension` but it didn't work because of some includes missing I think. I tried to fix it but I didn't get it to work in the end. Maybe I just missed something simple.

**Comment by marcusnaslund** [comment]
Hmm, the link above says `no additional dependency needs to be installed.`.

**Comment by jonathanudd** [comment]
I read that before trying to build it and was hopeful but it was not true I guess. Or as I said maybe I missed something. I can try again and see if I'm more successful this time.

**Comment by marcusnaslund** [comment]
We're not interested in Windows atm, and CircleCI/Appveyor are about to be replaced by print - so I'm closing this.
