### ISSUE TITLE
Vector2D doesn't work perfectly on Windows

### ISSUE THREAD

**Issue by marcusnaslund** [cogneco/ooc-kean#666]
It seems to work just fine on Linux, but `Vector2DTest` segfaults sometimes (albeit rarely) on Windows. This is either a problem with the implementation or the test itself.

**Comment by sebastianbaginski** [comment]
There is a problem with the test, it tries to access non-existing elements in vector:
```ooc
for (row in (sizeM + 1) .. sizeXL)
	for (column in (sizeM + 1) .. sizeXL)
		expect(vector2D[row, column], isNotTheValue)
```
`vector2D rowCount == sizeM` and here it tries to access elements at `sizeM + 1 ...`
Btw. it crashes on linux if you run it like `./test.sh collections/Vector2D -Dsafe`

**Comment by marcusnaslund** [comment]
Oh! Easy fix, then. :)

**Comment by sebastianbaginski** [comment]
After removing this it still crashes in next test case in `-Dsafe` mode, something is wrong with index calculation in vector2d operator[]:
> 11:02:56 Vector2D ....[Exception]: Accessing Vector2D index out of range in set operator

From vector2d:
```ooc
	operator []= (row, column: Int, item: T) {
		version (safe) {
			if (row >= this columnCount || row < 0 || column >= this rowCount || column < 0)
				raise("Accessing Vector2D index out of range in set operator")
		}
}

 // ... and in the test

for (row in 0 .. vector2D rowCount)
	for (column in 0 .. vector2D columnCount)
		vector2D[row, column] = row * vector2D columnCount + column

```

In the test `row` moves from zero to `rowCount` and in vector it is tested against `columnCount`.
Do you know who wrote this class ? Should we simply switch the variables in the test loops ?

**Comment by marcusnaslund** [comment]
The safety checks are wrong.

**Comment by marcusnaslund** [comment]
Maybe let's get @tomasmahlberg in here, since he wrote the class.

**Comment by sebastianbaginski** [comment]
OK, I'm signing off then.

**Comment by tomasmahlberg** [comment]
Yes, it seems the range checks are faulty here. This probably stems from the birth of this class when the ambiguous term capacity was used instead of count which caused some confusion.

The tests were adapted from the `Vector` tests which also seem to access indices out of range:
```ooc
heapVector resize(5)
expect(heapVector capacity, is equal to(5))
for (i in 0 .. 5)
	heapVector[i] = 5
for (i in 0 .. 5)
	expect(heapVector[i], is equal to(5))
isNotTheValue = is not equal to(5)
for (i in 6 .. 20)
	expect(heapVector[i], isNotTheValue)
```

**Comment by marcusnaslund** [comment]
Alright. @sebastianbaginski or @tomasmahlberg - will one of you place a PR to correct this?

**Comment by tomasmahlberg** [comment]
I can look at this. But I'm not sure what to do about the tests. What is the purpose of looking at elements that are out of range after a `resize`? Talking about `Vector` here.

**Comment by marcusnaslund** [comment]
I have no idea.

**Comment by sebastianbaginski** [comment]
I'd say this should not be in the tests, in safe mode we throw exception when index is out of range, so it is an "exceptional" situation that is not meant to happen.

**Comment by marcusnaslund** [comment]
Agreed. Take it out.

**Comment by tomasmahlberg** [comment]
#696.
