### ISSUE TITLE
Improve visibility of failed test case printouts

### ISSUE THREAD

**Issue by sebastianbaginski** [cogneco/ooc-kean#671]
It should be easy to find the failed test case

**Comment by davidhesselbom** [comment]
Try changing the color of the failure output.

**Comment by marcusnaslund** [comment]
`sdk/os/Terminal.ooc`

**Comment by sebastianbaginski** [comment]
@marcusnaslund since you are already on it I will remove this assignment from myself

**Comment by marcusnaslund** [comment]
@sebastianbaginski Oh, I do want to move that file out of the SDK, this gives me a good excuse. I'm on it :)

**Comment by sebastianbaginski** [comment]
What about writing something simple at the end of the test suite:
> ...
> 13:36:51 String .......... done in 0.00s, total: 21.62s
> 13:36:51 Double ............... done in 0.00s, total: 21.62s
> 13:36:51 Float ............... done in 0.00s, total: 21.62s
> Failed tests : 3 (Vector2D, BlockedQueue, SynchronizedQueue)

?

**Comment by marcusnaslund** [comment]
No `Fixture` instance knows if it's the last one, in that case the bash file has to be rewritten.

**Comment by sebastianbaginski** [comment]
OK, I see. So there could be a static string list in the Fixture class, on each failure the given Fixture instance adds its name to this static list, which then is printed in a static method at the program exit, registered as `atexit()` handler ?

**Comment by sebastianbaginski** [comment]
I mean like here https://github.com/cogneco/ooc-kean/pull/672

**Comment by marcusnaslund** [comment]
I'm not sure I like that over colouring where the error occurs. However, I am having no luck getting the coloring to work on Appveyor using escape sequences (even though it should). I leave this to you.

**Comment by sebastianbaginski** [comment]
I mean, this one *and* the coloring (in case someone does not want to scroll all the way up).

**Comment by sebastianbaginski** [comment]
OK, so maybe we should just skip the coloring and print something like a message separated by newlines so it is easy to find it.

**Comment by marcusnaslund** [comment]
Printing milliseconds in the time stamp and getting rid of `done in 0.27s, total: 21.62s` at the end of each line would help clear up as well, as I suggested in #603. Not sure what @davidhesselbom says about that, though.

**Comment by marcusnaslund** [comment]
According to here: http://help.appveyor.com/discussions/suggestions/197-support-ansi-color-codes
We should be able to use ANSI color codes, but while it works fine on my Linux terminal, Appveyor shows nothing.

**Comment by sebastianbaginski** [comment]
So you could get it to work on linux ? That's great, I think you should commit it anyway, it would be great to have it locally.

**Comment by marcusnaslund** [comment]
The `sdk` already supported it :) I'm going to lift that out in to kean, and then I'll add it to Fixture.

**Comment by thomasfanell** [comment]
Do we need the dots? Who counts them? I think we should remove the dots and pad the output, then it will be easier to distinguish failures. I also agree with @sebastianbaginski that we should aim for a summary at completion.

This is what the magic self-test looks like, while not perfect, I think it is far less clogged than ooc-kean's. It is also color coded, where 'passed' is green and 'failed' is red.
```
SyntaxTree.Declarations.Variable..................: passed
SyntaxTree.Expressions.Assignment.................: failed
  -> expected 'c', found 'b' [expect #2 in 'literal']
SyntaxTree.Expressions.Literals.CharacterLiteral..: passed
SyntaxTree.Expressions.Literals.NumberLiteral.....: failed
  -> expected '123456', found '12345' [expect #2 in 'binary']
  -> expected '543219', found '869136' [expect #2 in 'hexadecimal']
SyntaxTree.Expressions.Literals.CharacterLiteral..: passed
Utilitites.ArrayIterator..........................: passed
Utilitites.BufferedIterator.......................: passed
```

**Comment by thomasfanell** [comment]
Furthermore, would it be a good idea to indicate the namespace?
```
math/FloatBox2D........ : passed (0.2s)
io/CsvReader........... : passed (0.1s)
io/CsvWriter........... : passed (0.1s)
```

**Comment by davidhesselbom** [comment]
Removing the dots won't solve anything. You still need to know the length of all test names in order to be able to pad them all.

**Comment by thomasfanell** [comment]
magic is proudly using a fixed width for this.

**Comment by davidhesselbom** [comment]
If you're using a hard-coded, fixed width, then the dots shouldn't be a problem - just pad with spaces after the dots.

**Comment by thomasfanell** [comment]
No, padding with dots is much better as it provides added separation and it's easier to read line by line.

**Comment by sebastianbaginski** [comment]
https://github.com/cogneco/ooc-kean/pull/672 is merged and it was all I wanted when creating this issue, so closing it.
