### ISSUE TITLE
Implicit toString() and toText()

### ISSUE THREAD

**Issue by davidhesselbom** [cogneco/ooc-kean#681]
Currently, we do stuff like
```ooc
// x, y, z are Int, Float or something other than a String
println("Hello world " + x toString() + " " + y toString() +  " " + z toString())
```
Which is rather messy. 
```ooc
println("Hello world " + x + " " + y + " " + z)
```
is a lot neater, but it doesn't work.

Is it possible to override operators for `String` so that the right-hand argument is automatically converted to `String` if it isn't one already? Are there problems that could arise from such overloads?

EDIT: This applies to `toText`, too.
EDIT 2: Actually, we currently do things like this:
```ooc
// x, y, z are Int, Float or something other than a String
(xString, yString, zString) := (x toString(), y toString(), z toString())
println("Hello world " << xString >> " " & yString >>  " " & zString)
```

**Comment by marcusnaslund** [comment]
This isn't pretty, but we could probably do something like this?
```ooc
operator + (other: Int) -> This {
	converted := other toString()
	result := this + Text new(converted)
	converted free()
	result 
}
```

**Comment by davidhesselbom** [comment]
Something like that. It's not pretty, no, but it *would* clean up the code elsewhere. A lot. It would mean not having to create temporary variables for the strings.

**Comment by marcusnaslund** [comment]
I will try it and make sure nothing leaks (one day I'll understand these buffers).
