### ISSUE TITLE
Clean files in sdk/io

### ISSUE THREAD

**Issue by marcusnaslund** [cogneco/ooc-kean#692]
Add `this` where appropriate, remove not needed code.
We won't be using these classes forever, but for the forseeable future, so making them easier to maintain is a big plus. Throw out whatever isn't used in these files.

- [x] BinarySequence.ooc
- [x] BufferReader.ooc, BufferWriter.ooc
- [x] File.ooc
- [x] FileReader.ooc, FileWriter.ooc
- [x] Reader.ooc, Writer.ooc

**Comment by thomasfanell** [comment]
Should we keep the convention of having classes that are specific to a certain platform under the ```native``` namespace? I vote yes.

Example: ```source/io/native/FileUnix.ooc```

**Comment by marcusnaslund** [comment]
Hmm, `source/widgets` disagrees.

**Comment by thomasfanell** [comment]
I could live without it, but I think it's much cleaner since most often one only need to look at the parent.

**Comment by marcusnaslund** [comment]
I'd like to hear the opinions of @davidhesselbom and @simonmika because the same answer applies to moving `threading` as well.

**Comment by davidhesselbom** [comment]
I guess it would keep things clearer... but then again, should we do the same thing in `ooc/widgets`?

**Comment by simonmika** [comment]
Keep and where necessary introduce `native` folders.

**Comment by simonmika** [comment]
When it comes to `io` we should build heavily on the concepts used in https://github.com/cogneco/Kean. They work really well.

**Comment by marcusnaslund** [comment]
It doesn't seem to be possible to move these files because of dependencies in the sdk. Changed the issue to do some general cleanup so they're easier to maintain for the time being. If we ever get around to rewriting the io component from scratch we can discuss thinning it out even further.
