### ISSUE TITLE
free or gc_free?

### ISSUE THREAD

**Issue by davidhesselbom** [cogneco/ooc-kean#695]
`gc_free` and `gc_malloc` are useful if we want to be able to build with or without a GC. Since we have no plans on ever using a GC, though, why not just call `free` and `malloc` instead?

**Comment by thomasfanell** [comment]
I agree. I just thought about that when writing up the sample code for the issue I posted for rock.

**Comment by marcusnaslund** [comment]
Note: `gc_malloc` actually calls `calloc`, not `malloc`, which is why we have default values in ooc.

**Comment by davidhesselbom** [comment]
Well then, `calloc` instead of `gc_malloc`.

**Comment by marcusnaslund** [comment]
Since we've discussed this and decided on another approach I'm closing this and opening an appropriate issue.
