### ISSUE TITLE
Timer and Profiler do not work on Windows

### ISSUE THREAD

**Issue by marcusnaslund** [cogneco/ooc-kean#715]
As I was writing a test for `Timer` and `ClockTimer` (#714) I noticed that it kept failing on AppVeyor. I have now confirmed that `Timer` does indeed not work on Windows at all - which means `Profiler` also doesn't work.

The reason is that `Time runTimeMicro()` always returns `UINT_MAX` on Windows.

`ClockTimer` works well because it uses a different implementation.

**Comment by marcusnaslund** [comment]
Appearently `Timer` expects to get microsecond precision, but `runTimeMicro` in `sdk/os/Time.ooc` is not implemented on Windows. 

We can make this sdk function return `1000 * This runTime()` on windows, or explicitly use millisecond precision on windows using a version flag in `Timer`, or **always** use millisecond precision in `Timer`. @davidhesselbom ?

**Comment by davidhesselbom** [comment]
I dunno, I think microsecond precision is pretty important when you want to profile things... so I would rather fake precision under windows than reduce precision in linux.
