### ISSUE TITLE
cleanup, dispose, clean...

### ISSUE THREAD

**Issue by davidhesselbom** [cogneco/ooc-kean#727]
Now that we've finally gotten rid of `__destroy__`, the next thing to fix is the naming of the various other functions we use for cleanup, among them `dispose`, `cleanup`, and `clean`. There may be reasons why they shouldn't all be called the same thing (e.g. `free`), but generally, you shouldn't have to guess which one is used for a particular class.

**Comment by sebastianbaginski** [comment]
@davidhesselbom @marcusnaslund : which one should it be ? I can start fixing this.

**Comment by emilwestergren** [comment]
`dispose` looks like copied C# code, simply replace with `free`?

**Comment by davidhesselbom** [comment]
What about static cleanup functions?

**Comment by sebastianbaginski** [comment]
> What about static cleanup functions ?

I think you just made a decision ("static **cleanup** functions") ;)

**Comment by sebastianbaginski** [comment]
> Also free?

I think it is not possible to have a static and member function with the same name.

**Comment by simonmika** [comment]
Isn't it possible to have them with a regular overload `~all` or `~static`?

**Comment by sebastianbaginski** [comment]
Yes, it is possible to add a suffix to change the name of static `free` method.

**Comment by marcusnaslund** [comment]
Is there a decision on this?

**Comment by simonmika** [comment]
I think clean is not very clear so I lean towards having a static free even if it ends up looking like:
`Class free~recycled()`
or something.

**Comment by marcusnaslund** [comment]
@simonmika Are we going with `free~<something>()`?

**Comment by marcusnaslund** [comment]
For the record: We're going with `freeAll` or `free~all`, I'll see what looks best.
