### ISSUE TITLE
Generalize the bilinear interpolation method in raster classes

### ISSUE THREAD

**Issue by sebastianbaginski** [cogneco/ooc-kean#732]
https://github.com/cogneco/ooc-kean/pull/530 introduced bilinear rescaling for monochrome images. It should be generalized (possibly optimized) and used in other `Raster*` classes.

**Comment by marcusnaslund** [comment]
"Fixes part of..." also closes it?

**Comment by sebastianbaginski** [comment]
Looks like it :)

**Comment by marcusnaslund** [comment]
Ah, that wasn't the exact phrasing, but then you could probably write something like "This will ABSOLUTELY NOT fix #732" and it will close it. Good to know.
