### ISSUE TITLE
Clean math & geometry classes and covers

### ISSUE THREAD

**Issue by marcusnaslund** [cogneco/ooc-kean#739]
Most of these classes/covers were ported directly from their C# counterparts and haven't been maintained properly since then. A lot of code can be cleaned up, rearranged or removed to make these classes/covers easier to understand, bugfix and maintain:

- [x] Rearrange the order of methods and operators to make the code easier to read. Be consistent with the ordering (from the top) members, properties, constructors, `free`, public methods, private methods, operators.
- [x] Improve performance by changing `this[]`-calls to `thisPointer[]`-type-calls wherever needed.
- [x] Write short methods and properties on one line instead of three.
- [x] Remove unneccessary imports (like `structs/ArrayList`)
- [x] Add `toText()` and deprecate `toString()`: #774 

This applies to all files in `source/math` and `source/geometry`.

**Comment by sebastianbaginski** [comment]
@marcusnaslund @davidhesselbom  I think this issue is too big. Can we close it and open more detailed ones if needed ?

**Comment by marcusnaslund** [comment]
That's probably true, but I don't want one issue for every file... Can we make it better with some kind of checkbox list?

**Comment by davidhesselbom** [comment]
You can make
- [ ] one
- [ ] for
- [ ] every
- [ ] other
- [ ] issue
- [ ] you
- [ ] create

and put links to each issue next to a checkbox. If you want.

**Comment by sebastianbaginski** [comment]
I don't know, probably. When you opened this issue you had some concrete examples on mind, right ?

**Comment by marcusnaslund** [comment]
> When you opened this issue you had some concrete examples on mind, right ?

Right. I will try to update this to something more useful.

**Comment by thomasfanell** [comment]
> Right. I will try to update this to something more useful.

Fixed.
