### ISSUE TITLE
Is it possible to be smarter in Text slice()?

### ISSUE THREAD

**Issue by marcusnaslund** [cogneco/ooc-kean#747]
Is there really a smarter way, which this TODO comment is looking for in `Text.ooc`?
```ooc
if (this _buffer owner == Owner Receiver)
	result = result copy() // TODO: Could we be smarter here?
```
Creating this issue so it's not forgotten. If not, the comment should be removed.

**Comment by simonmika** [comment]
It requires the introduction of a reference counter. It is possible but still unclear whether it is something we want.
