### ISSUE TITLE
Angle function in FloatRotation3D is giving odd results.

### ISSUE THREAD

**Issue by niklasborwell** [cogneco/ooc-kean#751]
`rotation := FloatRotation3D createRotationZ(2)`
`println("%.10f" format(temp angle(temp)))`

The result is 0.0003452670, but of course the angle between two identical rotations should be zero.

**Comment by marcusnaslund** [comment]
Sounds like floating point behaviour.. no?

**Comment by niklasborwell** [comment]
I think the error seems to high, but I haven't confirmed it.

**Comment by marcusnaslund** [comment]
I checked the dot product, and it is approx. 0.9999999404, and the following `C` program
```c
float dotproduct = 0.9999999404f;
float result = acosf(fabsf(dotproduct));
printf("%.10f \n", result);
```
also prints 0.0003452670.
