### ISSUE TITLE
Clean up Event classes

### ISSUE THREAD

**Issue by marcusnaslund** [cogneco/ooc-kean#755]
- [x] `init ~nil` has the following comment: `FIXME: this is really a stupid way to create null pointer although no null text is required`. Is there something to actually fix here, and if so what?
- [x] There are `+` operators that are commented out. We generally do not keep commented-out code. Either fix it if we can or remove.
- [x] The names. Is `Event1` and `Event2` really the best we can do? (EDIT: Appearently, yes.)

**Comment by sebastianbaginski** [comment]
this, and check the issue no. 900 in the other project.

**Comment by marcusnaslund** [comment]
Ah, wonderful. Sounds like something you're going to tackle later then. :)

**Comment by sebastianbaginski** [comment]
We're going to talk about this with @simonmika soon.

**Comment by marcusnaslund** [comment]
Fixed in #1179
