### ISSUE TITLE
toString() methods in ooc-math has duplicate string conversions

### ISSUE THREAD

**Issue by tomasmahlberg** [cogneco/ooc-kean#759]
A lot of `toString` methods in the ooc-math library look something like this:
```ooc
toString: func -> String { "#{this width toString()}, #{this height toString()}" }
```
`#{x toString()}` effectvely converts to string twice and should be replaced by just `#{x}` or `x toString()`.

**Comment by davidhesselbom** [comment]
Yes, this is a mistake. This syntax also leaks memory, even if `toString()` is removed, and should probably to be replaced by `Text` anyway, so I suggest *not* cleaning this up.

**Comment by marcusnaslund** [comment]
Exactly, these will be replaced by a `ToText` soon enough.

**Comment by tomasmahlberg** [comment]
Perfect! I'll close this then.

**Comment by sebastianbaginski** [comment]
... and when we are done replacing `String` with `Text` we can rename `Text` to `String` and start again with new `Text` class :)
