### ISSUE TITLE
FloatPoint2DVectorList getMean() with indices

### ISSUE THREAD

**Issue by bettinaselig** [cogneco/ooc-kean#762]
Currently the function the function that is calculating the mean of elements with given indices is called `getMean()`:
```
getMean: func (indices: VectorList<Int>) -> FloatPoint2D
```
It would be nice if it is mentioned in the name that it depends on indices. Less confusing.

**Comment by marcusnaslund** [comment]
Any suggestions on the name?

**Comment by bettinaselig** [comment]
`getMeanOfIndices()`? `getMean~indices()`?
