### ISSUE TITLE
The need for Requires clauses in use files

### ISSUE THREAD

**Issue by marcusnaslund** [cogneco/ooc-kean#767]
For example, `ooc-collections.use` contains:
```
Requires: ooc-unit
Requires: ooc-base
Requires: ooc-sdk-lite
```
From what I heard they're "used" by a tool called *sam* but I don't quite understand what this tool does and why we need these lines at all. They don't seem to serve a purpose at the moment as they can be removed without any errors.

**Comment by simonmika** [comment]
They way forward here should be to have magic emit errors if we don't update these. It will give us a lot better dependency control and make solving circular dependencies way easier. @thomasfanell

**Comment by marcusnaslund** [comment]
We can consider @thomasfanell notified of this and so I'm closing this.
