### ISSUE TITLE
Inconsistent modulo operator

### ISSUE THREAD

**Issue by marcusnaslund** [cogneco/ooc-kean#768]
The `modulo` function in `Int`, `Int64`, and `Float` (and possibly others) are all inconsistent with each other. They should be corrected to comply with the following C# code from the original kean:
```csharp
public static int Modulo(int dividend, int divisor)
{
	if (dividend < 0)
		dividend += Integer.Ceiling(Integer.Absolute(dividend) / (float)divisor) * divisor;
	return dividend % divisor;
}
```
See the original discussion here: #508 

The ooc methods should *not* be static, though.

**Comment by davidhesselbom** [comment]
:+1:
