### ISSUE TITLE
Tests for Promise and PromiseCollector fail (too) often on AppVeyor

### ISSUE THREAD

**Issue by marcusnaslund** [cogneco/ooc-kean#771]
They run just fine when tested on a local Windows machine, but seem to crash often on AppVeyor. This comes and goes, so is likely dependant on varying levels of available resources. But this is of course not good anyway.

Any ideas on how to make sure the tests run fine on AppVeyor without limiting them too much locally are much appreciated.

**Comment by simonmika** [comment]
Stop using AppVeyor?

**Comment by marcusnaslund** [comment]
Are we not interested in Windows support anymore?

**Comment by simonmika** [comment]
Windows support is not that important. That might change but if it costs us time now I prefer not spending that time on it. On the other side, if there is a quick fix then fix it but if it takes forever drop Windows.

**Comment by marcusnaslund** [comment]
That would solve #760 as well.

**Comment by marcusnaslund** [comment]
@davidhesselbom - I guess you're the only one who can turn it off.

**Comment by davidhesselbom** [comment]
Done. I guess `appveyor.yml` should be deleted as well, then.

**Comment by davidhesselbom** [comment]
So... we can close this, I take it?

**Comment by marcusnaslund** [comment]
Place a PR that removes appveyor.yml and close it, I suggest.
