### ISSUE TITLE
Determine if we should remove RasterYuv422Semipacked createFrom()

### ISSUE THREAD

**Issue by marcusnaslund** [cogneco/ooc-kean#772]
This function starts with the comment
```
// TODO: Figure out what this function does and whether to remove it
```
It does not appear to be used anywhere.

**Comment by simonmika** [comment]
You should probably link to some code here.

**Comment by marcusnaslund** [comment]
Right. I'm talking about the `createFrom` function starting on line 37 of https://github.com/cogneco/ooc-kean/blob/master/source/draw/RasterYuv422Semipacked.ooc

**Comment by sebastianbaginski** [comment]
This one looks like one of `convertFrom` functions in other raster classes.

**Comment by simonmika** [comment]
So a name change and it should probably be a static method to.

**Comment by marcusnaslund** [comment]
Alright, nice easy fix.
