### ISSUE TITLE
Start replacing toString() with toText()

### ISSUE THREAD

**Issue by marcusnaslund** [cogneco/ooc-kean#774]
With the `parse` functions now taking `Text` instead of `String` arguments (in source/math) it is time to deprecate `toString()` and implement `toText()` throughout the library.

- [x] source/math
- [x] source/geometry

**Comment by marcusnaslund** [comment]
Actually, this should be done in `source/geometry` as well, so I'm reopening this.

**Comment by thomasfanell** [comment]
@marcusnaslund issue description modified
