### ISSUE TITLE
Remove VarArgs

### ISSUE THREAD

**Issue by marcusnaslund** [cogneco/ooc-kean#776]
In math.ooc, the `maximum` and `minimum` versions are not used, would leak memory, and force us to always write `minimum~two` instead of `minimum` everywhere in the code.

EDIT: We can probably get rid of the whole thing if we can figure out how to do `printfln()` and `format()` in another way.

**Comment by sebastianbaginski** [comment]
Do we want to keep the `VarArgs` cover ? If yes then some fixing will be needed, first of all the `free` method (to release memory allocated with malloc). I also do not understand why it assumes that on unix (not windows) every argument will have the size of `Class` ...

**Comment by marcusnaslund** [comment]
I discussed this briefly with @davidhesselbom , there doesn't seem to be a way to use them without leaking memory, and there is no type safety at all.
@simonmika ?

**Comment by sebastianbaginski** [comment]
There is a way if you have a function returning a vector of arguments instead of iterating. This is an overkill for two argument functions of course.
I'm not a big fan of `va_args` etc. anyway, just curious.

**Comment by simonmika** [comment]
Let's remove use of variable argument lists for now. We should try to fix it in the future though. When the language support is good it can be nice to have.

**Comment by niklasborwell** [comment]
@marcusnaslund This seems to be fixed with https://github.com/cogneco/ooc-kean/pull/818, correct?

**Comment by marcusnaslund** [comment]
My original idea was fixed (as you see in the title renaming just above your comment), but the issue drifted off into removing the use of `VarArgs` everywhere, including the cover itself. We're not quite there yet.

**Comment by niklasborwell** [comment]
Ok, I see.

**Comment by marcusnaslund** [comment]
Funny, this is now a copy of #741 - let's use that issue instead.
