### ISSUE TITLE
FloatBox2D, IntBox2D: Local variables have same names as properties.

### ISSUE THREAD

**Issue by bettinaselig** [cogneco/ooc-kean#814]
In the function `init()`, `intersection()` and `union()`, local variables with the names `left`, `top`, `width` and `height` are created. Since `FloatBox2D`, `IntBox2D` have properties with the same names this might cause confusion and there is a risk that rock chooses the wrong variable, see https://github.com/fasterthanlime/rock/issues/903.

Shall the local variables be renamed? 
@marcusnaslund @davidhesselbom @niklasborwell @sebastianbaginski

**Comment by davidhesselbom** [comment]
Just want to add that this happens in a large number of other places, not just there.

**Comment by bettinaselig** [comment]
We can decide here, if this is allowed. If we decide that is not allowed we can agree on that when we see it somewhere else that we make an issue and maybe refer to the decision made here.

**Comment by niklasborwell** [comment]
I vote not allowed. But it's not a very strong vote.

**Comment by bettinaselig** [comment]
I vote not allowed. Without reservation.

**Comment by sebastianbaginski** [comment]
Could be nice if the compiler rejected such code, but I think we're on our own with this one. Definitely should not be allowed.

**Comment by davidhesselbom** [comment]
Again, I would prefer if the compiler refused to let you compile `left` when you really mean `this left`. Removing the ambiguity would solve the problem.

**Comment by bettinaselig** [comment]
Confusion remains. But I also agree on that it should not be allowed to use `left` when you mean `this left`. Who can fix that?

**Comment by davidhesselbom** [comment]
Why does confusion remain? If you know that `left` cannot mean `this left`, what's left to confuse you?

**Comment by bettinaselig** [comment]
I think it's not very good style to use the name of a class variable/property for a local variable.

**Comment by niklasborwell** [comment]
Since the only one arguing for "allowed" has left the building, can we decide on "not allowed" and close/handle this issue?
@bettinaselig @sebastianbaginski @marcusnaslund

**Comment by marcusnaslund** [comment]
Not **preferred**, anyway. I agree with closing.

**Comment by bettinaselig** [comment]
(1) Closing and remembering as a guideline for future code
                       or
(2) Closing and fixing the mentioned functions
                       ?

**Comment by marcusnaslund** [comment]
As was pointed out, there's nothing to fix since it works. I vote closing and adding to my upcoming style guide.

**Comment by bettinaselig** [comment]
Sure.

**Comment by niklasborwell** [comment]
Agreed. We can fix it piece by piece.
