### ISSUE TITLE
Replace maximum~two and minimum~two => maximum and minimum

### ISSUE THREAD

**Issue by marcusnaslund** [cogneco/ooc-kean#821]
After #818 there is only one version of `maximum` and `minimum` and thus we can remove the `~two` suffix and clean up a lot of calls to those two functions.

**Comment by davidhesselbom** [comment]
Just in case you had a more complicated approach in mind, you can remove the suffix from the function declaration, and anything that calls is will cause the build to fail. Could be easier than trying to hunt them all down with a search.

**Comment by niklasborwell** [comment]
I'll do this unless someone else specifically wanted to do it.
