### ISSUE TITLE
Memory leaks in `open` methods in Raster images

### ISSUE THREAD

**Issue by sebastianbaginski** [cogneco/ooc-kean#842]
They were fixed here https://github.com/cogneco/ooc-kean/pull/810 but the fix caused a SIGABRT when running the tests on some machines (only @marcusnaslund s machine, in fact:))

**Comment by marcusnaslund** [comment]
We've found a way to get rid of that problem now. Are there any `open` left to fix?

**Comment by sebastianbaginski** [comment]
I think we fixed them all
