### ISSUE TITLE
Do not compare floats with equality operator

### ISSUE THREAD

**Issue by sebastianbaginski** [cogneco/ooc-kean#860]
We need to have some kind of `floatIsZero(x)`, `floatEquals(x, y)` functions and do not use equality operator to compare floats. 
For example this test for `FloatSize2D` will fail because of floating point rounding errors:
```ooc
almostZero := (0.1 + 0.1 + 0.1) - 0.3
empty := FloatSize2D new(almostZero, 0.1f)
expect(empty empty, is true)
```
It fails because `almostZero > 0`.

**Comment by sebastianbaginski** [comment]
@marcusnaslund @davidhesselbom @simonmika @emilwestergren @davidpiuva any ideas ? 
how did you handle this in C# ?
I usually have a set of functions like 
```c++
#ifndef __FLOAT_PRECISION
#define __FLOAT_PRECISION 0.0001f
#endif

bool fuzzyCompare(const float x, const float y) {
    return fabs(x-y) < __FLOAT_PRECISION;
}

bool fuzzyIsZero(const float x) {
    return fuzzyCompare(x, 0.0f);
}

```
etc.
I don't think we can override `operator ==` for floats.
So, set of functions in `math` module ?

**Comment by davidhesselbom** [comment]
Usually,
```ooc
			expect(someFloat, is equal to(anotherFloat) within(this precision))
```
It gets a lot trickier if you want to call call properties like `empty`, of course.

**Comment by davidpiuva** [comment]
No constant tolerance can handle each exponent for every problem domain so it must be given as argument.

**Comment by simonmika** [comment]
Add to the extensions on all floating point types:
```ooc
equals(other: This, within := 0.0001f) -> Bool { (this - other) absolute() < within
```
