### ISSUE TITLE
Definition of `empty` differs between FloatVector2D and FloatVector3D 

### ISSUE THREAD

**Issue by sebastianbaginski** [cogneco/ooc-kean#870]
```ooc
FloatVector3D: cover {
	empty ::= this x == 0 || this y == 0 || this z == 0
}
FloatVector2D: cover {
	empty ::= !(this x > 0 && this y > 0)
}
```
One of them allows negative sizes while other doesn't. I think they should do the same thing.
Which one should it be ?
@simonmika @davidhesselbom @bettinaselig @niklasborwell

**Comment by bettinaselig** [comment]
What is an empty vector?

**Comment by sebastianbaginski** [comment]
Accorrding to tests : 
```ooc
empty := FloatVector2D new()
expect(empty empty, is true)
```

**Comment by bettinaselig** [comment]
Ok, so it's a vector with `x=0` and `y=0`. Negative values are allowed. But since `FloatVector2D` used to be `FloatSize2D`, we need to be careful where it is used.

**Comment by sebastianbaginski** [comment]
I just need to know which one you want before fixing https://github.com/cogneco/ooc-kean/issues/860
So it should be:
```ooc
FloatVector3D: cover {
    empty ::= this x == 0 || this y == 0 || this z == 0
}
FloatVector2D: cover {
    empty ::= this x == 0 || this y == 0
}
```
Is that correct ?

**Comment by bettinaselig** [comment]
Yes, but before you change that someone needs to check everywhere what was supposed to be checked when calling `FloatVector2D empty`.

**Comment by bettinaselig** [comment]
Maybe we need a check `notNegative` additionally.

**Comment by sebastianbaginski** [comment]
OK. I will just leave it as it is for now.

**Comment by marcusnaslund** [comment]
Now that they're called `Vector` instead of `Size`, I don't think `empty` is such a good name. The mathematical term is `zero vector` or `null vector`.

**Comment by bettinaselig** [comment]
I agree with @marcusnaslund. There are some other properties in `FloatVector2D`/`IntVector2D` that does not really fit anymore...

**Comment by niklasborwell** [comment]
I agree with both of you. `empty` seems weird to me, especially with `!(this x > 0 && this y > 0)`, even for a size that was strange. A better name like Marcus suggestion or removal would get my vote.
There are also other properties that seems strange for a vector, like `area` and `volume`. What do you think, @marcusnaslund?

**Comment by marcusnaslund** [comment]
I am OK with a `area` and `volume` properties since you can think of them as the area (or volume) spanned by the parallellogram (or parallellepiped) having that vector as greatest diagonal. It should be clear to everyone that the vector itself has no area or volume.

**Comment by niklasborwell** [comment]
Ok, it seems we have two camps about that. But since it's kind of useful and already used in several places, I'll just accept it then. Just the `empty` property then.

**Comment by niklasborwell** [comment]
But the volume of a parallellepiped is not `this x * this y * this z`, so it assumes a 90 degree edges. Same for the 2D case.

**Comment by davidhesselbom** [comment]
Can you really define a parallellipiped with a single vector and expect anyone to know it's a parallellipiped?

**Comment by marcusnaslund** [comment]
I'm sorry, I of course mean a rectangle and a cuboid.

**Comment by simonmika** [comment]
Let us continue to define:
```ooc
 empty ::= this x == 0 || this y == 0 || this z == 0
```

**Comment by niklasborwell** [comment]
@simonmika Can you explain why? What is the purpose of the `empty` property?

**Comment by simonmika** [comment]
It is an indicator whether the area or volume is zero. Here is an example where it makes sense:
```ooc
region0 := IntBox2D new(0, 0, 1, 1)
region1 := IntBox2D new(1, 1, 1, 1)

overlaps := region0 intersection(region1) size empty
```

**Comment by emilwestergren** [comment]
In your example, shouldn't `empty` be a property of `IntBox2D` instead of `IntVector2D`?
```ooc
region0 := IntBox2D new(0, 0, 1, 1)
region1 := IntBox2D new(1, 1, 1, 1)

overlaps := region0 intersection(region1) empty
```

**Comment by niklasborwell** [comment]
Ok, so the `empty` property basically means something like
"If we assume that this vector is the longest diagonal in a cuboid, not a parallellipiped or any other possible shape, would that cuboid have a volume that is zero?"
I would say that is far from obvious. If this is supposed to be an implementation of a general displacement vector, I think this name is too general and doesn't belong in here. Like Emil said, it would be better in the box classes that are supposed to represent volumes and areas.

**Comment by simonmika** [comment]
Vectors represent volumes and areas. Boxes represent regions.

**Comment by marcusnaslund** [comment]
A box can be empty. A vector can be `zero`, as I said above. Why not stick to mathematical definitions where they exist?

**Comment by davidhesselbom** [comment]
`zero` implies `Vector2D new(0, 0)` to me...

**Comment by bettinaselig** [comment]
How shall `box` be defined? Are negative vectors allowed as `size`? At the moment they are. I think we need to decide on this first, before we can make a choice about `empty`.

**Comment by sebastianbaginski** [comment]
`empty` makes sense for areas or volumes but it doesn't for vectors. Why vector `[sqrt(2), 0]` should be `empty` while vector `[1, 1]` not ? It is the same vector (same displacement length), just different direction.
I think we need better name than `empty` for vector, and I agree `empty` should not be in the vector interface.

**Comment by sebastianbaginski** [comment]
Bump.
Can we decide on something, implement it and close this issue ?

**Comment by bettinaselig** [comment]
Can someone check where `empty` is used? I guess then it is easier to decide something.

**Comment by niklasborwell** [comment]
As far as I can tell, only once in transformApplier, and that one could just as well be a null/zero vector check.

**Comment by bettinaselig** [comment]
I also found it in `Box`. But I think we should define in `Box` what an empty box is and not in `Vector`.

**Comment by bettinaselig** [comment]
https://github.com/cogneco/ooc-kean/pull/1054
A suggestion, please comment!

**Comment by sebastianbaginski** [comment]
There is no more `empty` so closing the issue.
