### ISSUE TITLE
Quaternion test crashes in safe mode

### ISSUE THREAD

**Issue by sebastianbaginski** [cogneco/ooc-kean#873]
Run with `./test.sh math/Quaternion -Dsafe`. Test will crash in `Quaternion weightedMean` function. Last operation is attempt to add two matrices, one of them is null:
> 14:54:04 Quaternion .................................
> Program received signal SIGSEGV, Segmentation fault.
> 0x000000000047b3d8 in FloatMatrix__FloatMatrix___OP_ADD_ASS_This (this=..., 
>    other=...)
>   at ooc-kean/source/math/FloatMatrix.ooc:411
> 411        thisElements[i] += otherElements[i]

> (gdb) print thisElements
> $1 = (lang_Numbers__Float *) 0x718d50
> (gdb) print otherElements
> $2 = (lang_Numbers__Float *) 0x0

@marcusnaslund @thomasfanell git lists you two as last authors of Quaternion.ooc file. Any hints about this one ?

**Comment by sebastianbaginski** [comment]
`FloatEuclidTransformTest` crashes in the same method.

**Comment by sebastianbaginski** [comment]
@thomasfanell : Sorry I meant @tomasmahlberg :)

**Comment by tomasmahlberg** [comment]
Some `take`'s missing inside the `safe` check in the `+=` operator in FloatMatrix it seems... I'll fix it.
