### ISSUE TITLE
`stride` should be signed in `RasterPacked`

### ISSUE THREAD

**Issue by sebastianbaginski** [cogneco/ooc-kean#900]
Both `getFirstDerivative` methods in `RasterMonochrome` incorrectly uses `width` to access the pixel buffer with offset (thanks @tomasmahlberg). Implementation for reference:
```ooc
	getFirstDerivative: func (x, y: Int) -> (Float, Float) {
		step := 2
		sourceWidth := this width
		source := this buffer pointer + y * sourceWidth
		derivativeX := (8 * source[x + step] - 8 * source[x - step] + source[x - 2 * step] - source[x + 2 * step]) as Float / (12.0f * step)
		derivativeY := (8 * source[x + sourceWidth * step] - 8 * source[x - sourceWidth * step] + source[x - sourceWidth * 2 * step] - source[x + sourceWidth * 2 * step]) as Float / (12.0f * step)
		(derivativeX, derivativeY)
	}
```

`sourceWidth := this width` should be `sourceWidth := this stride`.
`stride` is unsigned in `RasterPacked`, so due to C promotion rules, this expression `x - sourceWidth * step` will also be unsigned. Which is a disaster as the offsets are meant to be negative in this method.
This bug can be simply fixed by having 
```ooc
sourceWidth := this stride as Int
```
But I think in the long run it's better to make `stride` a signed integer, to avoid problems like this one in the future.
@emilwestergren @davidhesselbom any thoughts ?

**Comment by davidhesselbom** [comment]
`UInt` is intended to communicate that something should never be negative, but the result is typically this: unexpected behavior. So I think your idea is a good idea.
