### ISSUE TITLE
Naming of taken variables of types using OwnedBuffer backend

### ISSUE THREAD

**Issue by tomasmahlberg** [cogneco/ooc-kean#922]
Now that we are using the `OwnedBuffer` to a greater extent there are often situations where one want to create a temporary taken variable for accessing properties and calling methods without having to explicitly `take()` every time. We should try to come up with a standard for naming these variables instead of having to add the suffix `Taken` which creates unnecessarily long variable names and bloats the code. Perhaps another short suffix can be used.

In some places, we are using one letter variable names, eg. `t := this take()`. We should come to a consensus on what to do in these cases.

**Comment by marcusnaslund** [comment]
We don't generally allow for one-letter variables, but I'm OK with this one. Any other suggestions? `thisTaken`?

@simonmika ?

**Comment by marcusnaslund** [comment]
Noone seems to mind, the exception `t := this take()` has been allowed in the style guide and noone has complained there either.
